// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../index.js";

/**
 * @example
 *     {
 *         namespace_id: "demo"
 *     }
 */
export interface CreateNamespaceRequest {
    /** Durable namespace id to create. */
    namespace_id: LoonFS.NamespaceId;
}
