// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../index.js";

/**
 * @example
 *     {
 *         namespace_id: "demo"
 *     }
 */
export interface CreateNamespaceRequest {
    /**
     * The access mode, fixed for the namespace's life. Defaults to
     * unrestricted.
     */
    access?: LoonFS.NamespaceAccess;
    /** Durable namespace id to create. */
    namespace_id: LoonFS.NamespaceId;
}
