// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../index.js";

/**
 * @example
 *     {
 *         namespace_id: "namespace_id"
 *     }
 */
export interface DeleteNamespaceRequest {
    /** Namespace id */
    namespace_id: string;
    /** Delete only if the namespace head is still at this sequence */
    expected_head_seq?: LoonFS.ChangeSeq;
}
