// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../index.js";

/**
 * @example
 *     {
 *         namespace_id: "namespace_id",
 *         new_namespace_id: "demo"
 *     }
 */
export interface ForkNamespaceRequest {
    /** Source namespace id */
    namespace_id: string;
    /** Durable namespace id for the fork target. */
    new_namespace_id: LoonFS.NamespaceId;
}
