// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         namespace_id: "namespace_id",
 *         path: "path"
 *     }
 */
export interface ListFileRevisionsRequest {
    /** Namespace id */
    namespace_id: string;
    /** Absolute file path */
    path: string;
    /** Maximum page size */
    limit?: number;
    /** Opaque file-revisions page cursor */
    cursor?: string;
}
