// This file was auto-generated by Fern from our API Definition.

import { FilesystemClient } from "./api/resources/filesystem/client/Client.js";
import { NamespacesClient } from "./api/resources/namespaces/client/Client.js";
import { QueryClient } from "./api/resources/query/client/Client.js";
import { SystemClient } from "./api/resources/system/client/Client.js";
import { UploadsClient } from "./api/resources/uploads/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace LoonFSClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class LoonFSClient {
    protected readonly _options: NormalizedClientOptions<LoonFSClient.Options>;
    protected _system: SystemClient | undefined;
    protected _filesystem: FilesystemClient | undefined;
    protected _query: QueryClient | undefined;
    protected _namespaces: NamespacesClient | undefined;
    protected _uploads: UploadsClient | undefined;

    constructor(options: LoonFSClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    public get system(): SystemClient {
        return (this._system ??= new SystemClient(this._options));
    }

    public get filesystem(): FilesystemClient {
        return (this._filesystem ??= new FilesystemClient(this._options));
    }

    public get query(): QueryClient {
        return (this._query ??= new QueryClient(this._options));
    }

    public get namespaces(): NamespacesClient {
        return (this._namespaces ??= new NamespacesClient(this._options));
    }

    public get uploads(): UploadsClient {
        return (this._uploads ??= new UploadsClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
            },
            requestOptions,
        );
    }
}
