// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../index.js";

/**
 * @example
 *     {
 *         namespace_id: "namespace_id",
 *         commit_id: "c_f3a9c2d4b6e8417a90c5d2f8e1b7a6c0",
 *         operations: [{
 *                 kind: "copy_by_inode",
 *                 destination_display_name: "report.txt",
 *                 destination_parent_inode_id: "ino_123",
 *                 inode_id: "ino_123"
 *             }]
 *     }
 */
export interface CommitRequest {
    /** Namespace id */
    namespace_id: string;
    /** Caller-supplied idempotency key for the whole request. */
    commit_id: LoonFS.CommitId;
    /** The proofs for new external content references in this request. */
    content_tokens?: LoonFS.ContentToken[];
    /** The caller annotation that forms part of the commit identity. */
    message?: string;
    /** The non-empty ordered operations to commit atomically. */
    operations: LoonFS.FilesystemOperation[];
    /** Ordered admission conditions evaluated before any operations. */
    preconditions?: LoonFS.CommitPrecondition[];
}
