// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         namespace_alias: "namespace_alias",
 *         pattern: "pattern"
 *     }
 */
export interface GrepRequest {
    /** Application namespace alias */
    namespace_alias: string;
    /** Pattern in the Rust `regex` crate's dialect. Its UTF-8 encoding must be at most 1024 bytes. */
    pattern: string;
    /** Match case-insensitively (`true` or `false`). Defaults to `false`. */
    case_insensitive?: boolean;
    /** Complete absolute path used to restrict matches. */
    path_prefix?: string;
    /** Permit a capped exhaustive scan when the pattern has no required grams (`true` or `false`). Defaults to `false`. */
    allow_scan?: boolean;
    /** Return indexed-only results when the unindexed tail exceeds the scan budget (`true` or `false`). Defaults to `false`. */
    allow_stale?: boolean;
    /** Maximum matches per page */
    limit?: number;
    /** Opaque grep page cursor */
    cursor?: string;
}
