// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         namespace_alias: "namespace_alias",
 *         path: "path"
 *     }
 */
export interface ListFileRevisionsRequest {
    /** Application namespace alias */
    namespace_alias: string;
    /** Absolute file path */
    path: string;
    /** Maximum page size */
    limit?: number;
    /** Opaque file-revisions page cursor */
    cursor?: string;
}
