// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../core/index.js";
import * as errors from "../../errors/index.js";
import type * as LoonFS from "../index.js";

export class InternalServerError extends errors.LoonFSError {
    public declare readonly body: LoonFS.ErrorResponse;

    constructor(body: LoonFS.ErrorResponse, rawResponse?: core.RawResponse) {
        super({
            message: "InternalServerError",
            statusCode: 500,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, new.target.prototype);
        if (Error.captureStackTrace) {
            Error.captureStackTrace(this, this.constructor);
        }

        this.name = "InternalServerError";
    }
}
