// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../index.js";

/**
 * @example
 *     {
 *         namespace_alias: "namespace_alias",
 *         snapshot_id: "pin_00000000000000000001-0000000000000002"
 *     }
 */
export interface DeleteSnapshotRequest {
    /** Application namespace alias */
    namespace_alias: string;
    /** Snapshot id */
    snapshot_id: LoonFS.SnapshotId;
}
