// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         namespace_alias: "namespace_alias",
 *         snapshot_id: "snapshot_id",
 *         ttl_ms: 1000000
 *     }
 */
export interface ExtendSnapshotRequest {
    /** Application namespace alias */
    namespace_alias: string;
    /** Snapshot id */
    snapshot_id: string;
    /** Requested lifetime from the server's current time, in milliseconds. */
    ttl_ms: number;
}
