// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../index.js";

/**
 * @example
 *     {
 *         namespace_alias: "namespace_alias",
 *         snapshot_id: "pin_00000000000000000001-0000000000000002",
 *         ttl_ms: 1000000
 *     }
 */
export interface ExtendSnapshotRequest {
    /** Application namespace alias */
    namespace_alias: string;
    /** Snapshot id */
    snapshot_id: LoonFS.SnapshotId;
    /** Requested lifetime from the server's current time, in milliseconds. */
    ttl_ms: number;
}
