// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         namespace_alias: "namespace_alias"
 *     }
 */
export interface ListSnapshotsRequest {
    /** Application namespace alias */
    namespace_alias: string;
    /** Maximum page size */
    limit?: number;
    /** Opaque snapshot-list page cursor */
    cursor?: string;
}
