// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../index.js";

/**
 * @example
 *     {
 *         mount: "mount",
 *         body: {
 *             mode: "service_proxied"
 *         }
 *     }
 */
export interface BeginUploadBody {
    /** Application mount name */
    mount: string;
    body: LoonFS.BeginUploadRequest;
}
