// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         namespace_alias: "namespace_alias",
 *         upload_id: "upload_id"
 *     }
 */
export interface GetUploadRequest {
    /** Application namespace alias */
    namespace_alias: string;
    /** Upload session id */
    upload_id: string;
}
