// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../index.js";

/**
 * @example
 *     {
 *         namespace_alias: "namespace_alias",
 *         upload_id: "upload_id",
 *         parts: [{
 *                 checksum: {
 *                     algorithm: "sha256",
 *                     value: "value"
 *                 },
 *                 part_number: 1
 *             }]
 *     }
 */
export interface SignUploadPartsRequest {
    /** Application namespace alias */
    namespace_alias: string;
    /** Upload session id */
    upload_id: string;
    /** The parts to authorize; repeated part numbers replace their previous uploads. */
    parts: LoonFS.UploadPartChecksumClaim[];
}
