// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * A validated map from principal to rights, limited to
 * [`MAX_ACCESS_GRANT_ENTRIES`] entries and [`MAX_ACCESS_GRANTS_PRINCIPAL_BYTES`]
 * bytes of principal ids. No entry has an empty set of rights. Decoding
 * rejects repeated principals.
 */
export type AccessGrants = Record<string, LoonFS.AccessRights>;
