// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * A set of rights. Encoded as distinct names in `read`, `history`, `write`,
 * `create`, `remove`, `share`, `manage`, `admin` order. Decoding accepts any
 * order and rejects repeated names.
 */
export type AccessRights = LoonFS.AccessRight[];
