// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Result of advancing the retention floor.
 */
export interface AdvanceRetentionResponse {
    /** New minimum sequence for incremental replay. */
    retention_floor_seq: LoonFS.ChangeSeq;
}
