// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * A validated attribute map limited to 100 entries and 65,536 total key and
 * value UTF-8 bytes.
 *
 * Construction and decoding reject values over these limits; an empty map
 * represents cleared attributes.
 */
export type Attributes = Record<string, LoonFS.AttributeValue>;
