// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Kind-specific metadata for an authoritative path entry.
 */
export type AuthoritativePathEntryKind = LoonFS.AuthoritativePathEntryKind.Dir | LoonFS.AuthoritativePathEntryKind.File;

export namespace AuthoritativePathEntryKind {
    export interface Dir extends LoonFS.AuthoritativePathEntryDirectory {
        inode_kind: "dir";
    }

    export interface File extends LoonFS.AuthoritativePathEntryFile {
        inode_kind: "file";
    }
}
