// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Metadata for one path returned by stat and directory-listing operations.
 *
 * File entries include the current revision and content details. Directory
 * entries do not. Attribute fields are included only when requested and are
 * serialized at the top level of the entry. Callers can pass
 * `attributes_revision_no` as `expected_attributes_revision_no` when updating
 * attributes.
 */
export interface AuthoritativePathEntry extends LoonFS.AttributesProjection {
    /**
     * Time the inode was created, in Unix milliseconds. Sequence numbers
     * determine order.
     */
    created_at_ms: number;
    /** Actor that created this inode, as supplied by the application. */
    created_by: LoonFS.ActorRef;
    /** Stored display name for this path component, absent for the nameless root. */
    display_name?: LoonFS.DisplayName | undefined;
    /** Namespace head sequence this answer was read from. */
    head_seq: LoonFS.ChangeSeq;
    /** Stable inode ID within a namespace */
    inode_id: string;
    /** Namespace that was read. */
    namespace_id: LoonFS.NamespaceId;
    /** Stable inode ID within a namespace */
    parent_inode_id?: string | undefined;
    /** Absolute path as rendered from stored display names. */
    path: LoonFS.AbsolutePath;
}
