// This file was auto-generated by Fern from our API Definition.

/**
 * A directory, which has no revision payload in v0.
 *
 * The entry tag reuses [`InodeKind`]'s wire vocabulary.
 */
export type AuthoritativePathEntryDirectory = {};
