// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * A file and its current revision summary.
 */
export interface AuthoritativePathEntryFile {
    /** Current content reference. */
    content_ref: LoonFS.ContentRef;
    /**
     * Time of the current revision, in Unix milliseconds. Revision
     * sequences determine order.
     */
    revision_committed_at_ms: number;
    /** Actor responsible for the current revision. */
    revision_committed_by: LoonFS.ActorRef;
    /** Current file revision number. */
    revision_no: LoonFS.RevisionNo;
    /**
     * Current file size in bytes.
     *
     * This remains explicit even though `content_ref` also carries the
     * length because callers sort directory listings by this field.
     */
    size_bytes: number;
}
