// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Authoritative metadata for one visible path.
 *
 * This is the result shape for stat/list style reads. The entry kind carries
 * the file-only revision and content summary, so a directory cannot carry a
 * partial file payload. Attributes are likewise projected as one value or
 * omitted as one value, while serializing as prefixed sibling fields.
 * The attribute revision is read independently — clients feed it to
 * `expected_attributes_revision_no` on the next write without touching the
 * values — so this is a prefixed-sibling projection rather than a value
 * consumed as one nested unit.
 */
export interface AuthoritativePathEntry extends LoonFS.AttributesProjection {
    /**
     * Time the inode was created, in Unix milliseconds. Sequence numbers
     * determine order.
     */
    created_at_ms: number;
    /** Actor that created this inode, as supplied by the application. */
    created_by: LoonFS.ActorRef;
    /** Stored display name for this path component, absent for the nameless root. */
    display_name?: LoonFS.DisplayName | undefined;
    /** Namespace head sequence this answer was read from. */
    head_seq: LoonFS.ChangeSeq;
    /** Stable inode ID within a namespace */
    inode_id: string;
    /** Namespace that was read. */
    namespace_id: LoonFS.NamespaceId;
    /** Stable inode ID within a namespace */
    parent_inode_id?: string | undefined;
    /** Absolute path as rendered from stored display names. */
    path: LoonFS.AbsolutePath;
}
