// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Response to starting an upload session, tagged by transport mode.
 *
 * Each variant contains only the fields needed by that transport. Unknown
 * response fields are accepted for forward compatibility.
 */
export type BeginUploadResponse =
    | LoonFS.BeginUploadResponse.ServiceProxied
    | LoonFS.BeginUploadResponse.DirectPut
    | LoonFS.BeginUploadResponse.DirectMultipart;

export namespace BeginUploadResponse {
    export interface ServiceProxied extends LoonFS.BeginUploadResponseServiceProxied {
        mode: "service_proxied";
    }

    export interface DirectPut extends LoonFS.BeginUploadResponseDirectPut {
        mode: "direct_put";
    }

    export interface DirectMultipart extends LoonFS.BeginUploadResponseDirectMultipart {
        mode: "direct_multipart";
    }
}
