// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * A request to start an upload session for one required transport mode.
 */
export type BeginUploadRequest =
    | LoonFS.BeginUploadRequest.DirectMultipart
    | LoonFS.BeginUploadRequest.DirectPut
    | LoonFS.BeginUploadRequest.ServiceProxied;

export namespace BeginUploadRequest {
    export interface DirectMultipart extends LoonFS.BeginUploadDirectMultipart {
        mode: "direct_multipart";
    }

    export interface DirectPut extends LoonFS.BeginUploadDirectPut {
        mode: "direct_put";
    }

    export interface ServiceProxied extends LoonFS.BeginUploadServiceProxied {
        mode: "service_proxied";
    }
}
