// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * A short-lived capability to read one file's content object, plus
 * everything the reader needs to check what arrives.
 *
 * The raw object key is deliberately not here, exactly as it is not in a
 * `direct_put` grant: a client learns a URL that expires, not an address it
 * can revisit.
 *
 * The grant names one immutable content object, so it does not go stale
 * when the path moves on. A commit that replaces the file writes a new
 * object and leaves this one alone; what the capability reads is what the
 * requested revision held when the grant was issued, and the reference
 * says which bytes those are.
 */
export interface BeginDownloadResponse {
    /** Short-lived read capability the client uses without learning the raw object key. */
    access: LoonFS.ObjectTransferAccess;
    /**
     * Identity, byte length, and checksum evidence for the object the
     * capability reads. A reader checks the bytes it receives against
     * `size_bytes` and recomputes `checksum.algorithm` over the complete
     * payload.
     */
    content_ref: LoonFS.ContentRef;
    /** Namespace that was read. */
    namespace_id: LoonFS.NamespaceId;
    /** Absolute path as rendered from stored display names. */
    path: LoonFS.AbsolutePath;
    /** Revision the capability reads, resolved from the request. */
    revision_no: LoonFS.RevisionNo;
}
