// This file was auto-generated by Fern from our API Definition.

/**
 * Write the object in parts through presigned part uploads.
 */
export interface BeginUploadDirectMultipart {
    /**
     * Byte length of every part except the last. The server uses its
     * default when this is omitted.
     */
    part_size_bytes?: number | undefined;
}
