// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * One presigned request writes the whole object.
 */
export interface BeginUploadResponseDirectPut {
    /** The object this session writes, and the capability to write it. */
    direct_put: LoonFS.DirectPutUpload;
    /** Namespace authorized to consume the eventual staged content. */
    namespace_id: LoonFS.NamespaceId;
    /** Durable session identity used by subsequent completion calls. */
    upload_id: LoonFS.UploadId;
}
