// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Write the whole object through one presigned request. The server
 * signs exactly these bytes into the write it authorizes, so the claim
 * is required.
 */
export interface BeginUploadDirectPut {
    /** Byte length and digest of the payload about to be written. */
    content: LoonFS.UploadContentClaim;
}
