// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Request to start an upload session, tagged by transport mode.
 *
 * Each variant contains only fields valid for that transport, so invalid
 * combinations are rejected during decoding. The `mode` field is required.
 */
export type BeginUploadRequest =
    | LoonFS.BeginUploadRequest.ServiceProxied
    | LoonFS.BeginUploadRequest.DirectPut
    | LoonFS.BeginUploadRequest.DirectMultipart;

export namespace BeginUploadRequest {
    export interface ServiceProxied extends LoonFS.BeginUploadServiceProxied {
        mode: "service_proxied";
    }

    export interface DirectPut extends LoonFS.BeginUploadDirectPut {
        mode: "direct_put";
    }

    export interface DirectMultipart extends LoonFS.BeginUploadDirectMultipart {
        mode: "direct_multipart";
    }
}
