// This file was auto-generated by Fern from our API Definition.

/**
 * The API groups, features, and limits advertised by a deployment.
 */
export interface CapabilityDocument {
    /** The advertised `group/version` API groups, each with every required operation implemented. */
    api_groups: string[];
    /** The named features supported by this deployment, with absent keys treated as unsupported. */
    features?: Record<string, boolean> | undefined;
    /** Advisory numeric limits clients may use to pre-validate requests. */
    limits?: Record<string, number> | undefined;
    /** The protocol version, `v0`. */
    protocol_version: string;
}
