// This file was auto-generated by Fern from our API Definition.

/**
 * A deployment's self-description (API spec, "Capability discovery").
 *
 * A remote client fetches this from `GET /v0/capabilities` and caches it; an
 * embedded engine exposes the same document as a constant. SDK gating logic
 * is therefore identical for both backends: check [`supports`] or
 * [`has_profile`], and treat a `not_supported` error as authoritative when
 * the two disagree.
 *
 * [`supports`]: CapabilityDocument::supports
 * [`has_profile`]: CapabilityDocument::has_profile
 */
export interface CapabilityDocument {
    /**
     * Named features and whether this deployment supports them. An absent
     * key means unsupported.
     */
    features?: Record<string, boolean> | undefined;
    /** Advisory numeric limits clients may use to pre-validate requests. */
    limits?: Record<string, number> | undefined;
    /**
     * Advertised profiles, each `plane/version`. All-or-nothing: every
     * required op of an advertised profile is implemented.
     */
    profiles: string[];
    /** The protocol generation, currently `v0`. */
    protocol_version: string;
}
