// This file was auto-generated by Fern from our API Definition.

/**
 * Sequence number assigned to a namespace commit. It determines the order in which commits become visible.
 */
export type ChangeSeq = number;
