// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * A fork target retaining its source basis for one fork attempt.
 */
export interface CheckpointOwnerFork {
    /** The target namespace whose existence retains this checkpoint. */
    target_namespace_id: LoonFS.NamespaceId;
}
