// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * One checkpoint resource, reported from what its durable record carries.
 */
export interface Checkpoint {
    /** Durable checkpoint id used to address the checkpoint for release. */
    checkpoint_id: LoonFS.CheckpointId;
    /** Sequence covered by the checkpoint's pinned basis. */
    checkpoint_seq: LoonFS.ChangeSeq;
    /** Time the checkpoint record was created, in Unix milliseconds. */
    created_at_ms: number;
    /**
     * When garbage collection may release the record without being asked,
     * in Unix milliseconds. Absent means the pin holds until it is
     * released. An instant already in the past is a record whose expiry
     * has passed and which no collection pass has reached yet: it is still
     * a root, so it is still listed.
     */
    expires_at_ms?: number | undefined;
    /** Manifest pinned by the checkpoint. */
    manifest_no: LoonFS.ManifestNo;
    /** Namespace that owns the checkpoint. */
    namespace_id: LoonFS.NamespaceId;
    /** Who owns the checkpoint, including the label carried by a user pin. */
    owner: LoonFS.CheckpointOwnerSummary;
}
