// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * A fork target keeping its source basis alive for the length of one
 * fork attempt.
 */
export interface CheckpointOwnerFork {
    /** Namespace whose continued existence keeps this pin standing. */
    target_namespace_id: LoonFS.NamespaceId;
}
