// This file was auto-generated by Fern from our API Definition.

/**
 * An operator-created pin, deleted by id or by its own expiry.
 */
export interface CheckpointOwnerUser {
    /** The non-unique label recorded by the creator. */
    name: string;
}
