// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * One checkpoint resource described by its durable record.
 */
export interface Checkpoint {
    /** Namespace sequence captured by the checkpoint. */
    captured_seq: LoonFS.ChangeSeq;
    /** Durable checkpoint id used to address the checkpoint for deletion. */
    checkpoint_id: LoonFS.CheckpointId;
    /** Time the checkpoint record was created, in Unix milliseconds. */
    created_at_ms: number;
    /** Expiry in Unix milliseconds; collection waits one further grace window. */
    expires_at_ms?: number | undefined;
    /** Manifest pinned by the checkpoint. */
    manifest_no: LoonFS.ManifestNo;
    /** Namespace that owns the checkpoint. */
    namespace_id: LoonFS.NamespaceId;
    /** Who owns the checkpoint, including the label carried by a user pin. */
    owner: LoonFS.CheckpointOwnerSummary;
}
