// This file was auto-generated by Fern from our API Definition.

/**
 * Supported checksum algorithms.
 *
 * The enclosing value defines which bytes a checksum covers. Unknown
 * algorithms fail to decode because every in-memory `ChecksumAlgorithm` must
 * be recomputable by this build. Adding a variant also requires adding its
 * implementation.
 */
export const ChecksumAlgorithm = {
    Sha256: "sha256",
    Crc64Nvme: "crc64nvme",
    Crc32C: "crc32c",
} as const;
export type ChecksumAlgorithm = (typeof ChecksumAlgorithm)[keyof typeof ChecksumAlgorithm];
