// This file was auto-generated by Fern from our API Definition.

/**
 * An application-created read view.
 */
export interface CheckpointOwnerSnapshot {
    /** A label that does not need to be unique. */
    name: string;
}
