// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Requires a visible inode to retain the binding the caller read.
 */
export interface CommitPreconditionInodeBinding {
    /** Binding version observed by the caller. */
    expected_binding_version: LoonFS.BindingVersion;
    /** Inode whose binding the caller read. */
    inode_id: LoonFS.InodeId;
}
