// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Requires a visible inode with the access revision the caller read.
 */
export interface CommitPreconditionAccessRevision {
    /** Access revision observed by the caller. */
    expected_access_revision_no: LoonFS.AccessRevisionNo;
    /** Inode whose state the caller read. */
    inode_id: LoonFS.InodeId;
}
