// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Result of one commit.
 *
 * Every commit resolves to this envelope — path-oriented operations and
 * explicit commits, embedded or remote. The commit id is the caller's
 * reconciliation handle: resubmitting the same request with the same id
 * replays this result instead of committing twice.
 *
 * The response includes the same attribution and events as
 * [`CommittedChange`], including IDs created by the commit.
 */
export interface CommitResponse {
    /**
     * Idempotency key the commit landed under: caller-supplied, or
     * generated on the caller's behalf when the request carried none.
     */
    commit_id: LoonFS.CommitId;
    /**
     * Wall-clock stamp of the commit, in Unix milliseconds.
     * Observational: `committed_seq` is the order.
     */
    committed_at_ms: number;
    /** Actor responsible for the commit, as supplied by the application. */
    committed_by: LoonFS.ActorRef;
    /** Sequence number where the commit became visible. */
    committed_seq: LoonFS.ChangeSeq;
    /**
     * Semantic filesystem events in commit order. This is omitted only when
     * replaying a commit whose WAL history is no longer retained.
     */
    events?: LoonFS.FilesystemChange[] | undefined;
    /**
     * Caller annotation, omitted when absent and carrying no filesystem
     * semantics.
     */
    message?: string | undefined;
    /** Namespace that changed. */
    namespace_id: LoonFS.NamespaceId;
}
