// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Admission conditions checked against the candidate's pre-state before its operations.
 * The pre-state head sequence is the last admitted commit's sequence in the batch,
 * or the batch's base head sequence when no earlier candidate was admitted.
 */
export type CommitAssertion =
    | LoonFS.CommitAssertion.Attributes
    | LoonFS.CommitAssertion.Binding
    | LoonFS.CommitAssertion.FileRevision
    | LoonFS.CommitAssertion.NamespaceHead;

export namespace CommitAssertion {
    export interface Attributes extends LoonFS.CommitAssertionAttributes {
        kind: "attributes";
    }

    export interface Binding extends LoonFS.CommitAssertionBinding {
        kind: "binding";
    }

    export interface FileRevision extends LoonFS.CommitAssertionFileRevision {
        kind: "file_revision";
    }

    export interface NamespaceHead extends LoonFS.CommitAssertionNamespaceHead {
        kind: "namespace_head";
    }
}
