// This file was auto-generated by Fern from our API Definition.

/**
 * Client-supplied idempotency key for one logical commit.
 *
 * Reuse the same `CommitId` when retrying the same request. The accepted
 * grammar is 1 to 128 lowercase ASCII letters, digits, dots, underscores,
 * or hyphens, starting with a letter or digit. [`CommitId::generate`] returns
 * `c_<32 lowercase hex>`, but callers may supply any value in that grammar.
 */
export type CommitId = string;
