// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * One uploaded part accepted by the object-store provider.
 */
export interface CompletedUploadPart {
    /** Checksum the part was signed and accepted with. */
    checksum: LoonFS.Checksum;
    /** Entity tag the provider returned for the accepted part. */
    etag: string;
    /** One-based part number. */
    part_number: number;
}
