// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Request to complete an upload session.
 *
 * `mode` must match the mode used to start the session. Service-proxied and
 * direct-PUT uploads need no other fields. Direct multipart uploads also
 * include the completed parts and the expected content details.
 */
export type CompleteUploadRequest =
    | LoonFS.CompleteUploadRequest.ServiceProxied
    | LoonFS.CompleteUploadRequest.DirectPut
    | LoonFS.CompleteUploadRequest.DirectMultipart;

export namespace CompleteUploadRequest {
    export interface ServiceProxied extends LoonFS.CompleteUploadServiceProxied {
        mode: "service_proxied";
    }

    export interface DirectPut extends LoonFS.CompleteUploadDirectPut {
        mode: "direct_put";
    }

    export interface DirectMultipart extends LoonFS.CompleteUploadDirectMultipart {
        mode: "direct_multipart";
    }
}
