// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Complete a direct multipart upload.
 */
export interface CompleteUploadDirectMultipart {
    /** Expected length and checksum of the assembled object. */
    content: LoonFS.UploadContentClaim;
    /** Uploaded parts in ascending part order. */
    parts: LoonFS.CompletedUploadPart[];
}
