// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Identifies a chain prefix by its owner, content id, size, and checksum.
 */
export interface ContentRef {
    /** Mandatory checksum over the referenced bytes. */
    checksum: LoonFS.Checksum;
    /** Immutable identity of the content; with the owner, it determines the object key. */
    content_id: LoonFS.ContentId;
    /** Content strategy used by the referenced content. */
    kind: LoonFS.ContentRefKind;
    /** Namespace that originally wrote the bytes. */
    owner_namespace_id: LoonFS.NamespaceId;
    /** Byte length of the referenced bytes, a prefix of the content object. */
    size_bytes: number;
}
