// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * A presigned URL for one content object.
 *
 * The URL expires at `access.expires_at_ms`; later path changes do not change the object.
 */
export interface CreateDownloadResponse {
    /** Short-lived read capability the client uses without learning the raw object key. */
    access: LoonFS.ObjectTransferAccess;
    /** The identity, byte length, and checksum of the object to download. */
    content_ref: LoonFS.ContentRef;
    /** Namespace that was read. */
    namespace_id: LoonFS.NamespaceId;
    /** Absolute path as rendered from stored display names. */
    path: LoonFS.AbsolutePath;
    /** Revision the capability reads, resolved from the request. */
    revision_no: LoonFS.RevisionNo;
}
