// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Result of creating a checkpoint.
 */
export interface CreateCheckpointResponse extends LoonFS.Checkpoint {
    /** Namespace that was checkpointed. */
    namespace_id: LoonFS.NamespaceId;
}
