// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Result of deleting a namespace.
 */
export interface DeleteNamespaceResponse {
    /**
     * The head's last committed sequence; the delete linearized
     * immediately after it, so this is where history ended.
     */
    head_seq: LoonFS.ChangeSeq;
    /** Namespace whose history ended. */
    namespace_id: LoonFS.NamespaceId;
}
