// This file was auto-generated by Fern from our API Definition.

/**
 * Objects deleted by one GC pass, grouped by object family. Every field is
 * present, including zero counts.
 */
export interface DeletedObjectCounts {
    /** Released checkpoint records deleted after their grace window. */
    checkpoint_records: number;
    /**
     * Content objects deleted after their completed upload session passed
     * the reclamation grace period and no reachable data referenced them.
     * Cleanup of abandoned sessions is not counted here.
     */
    content_objects: number;
    /** Unreferenced manifests deleted. */
    manifests: number;
    /** Unreferenced metadata segments deleted. */
    metadata_segments: number;
    /** Upload-session control objects deleted after the reap window. */
    upload_sessions: number;
    /** Unreferenced WAL segments deleted. */
    wal_segments: number;
}
