// This file was auto-generated by Fern from our API Definition.

/**
 * Object counts deleted by one garbage-collection pass, grouped by family.
 */
export interface DeletedObjectCounts {
    /** Content objects no retained view names, deleted once older than the grace window. */
    content_objects: number;
    /** Unreferenced manifests deleted. */
    manifests: number;
    /** Unreferenced metadata segments deleted. */
    metadata_segments: number;
    /** Listed content objects deleted from a retired namespace. */
    retired_content_objects: number;
    /** Store temporary objects deleted once older than the grace window. */
    temporary_objects: number;
    /** Upload-session control objects deleted after the reap window. */
    upload_sessions: number;
    /** Unreferenced WAL objects deleted. */
    wal_objects: number;
}
