// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Identifies the checkpoint record that was deleted.
 */
export interface DeleteCheckpointResponse {
    /** Deleted checkpoint record. */
    checkpoint_id: LoonFS.PinId;
    /** Namespace the checkpoint belonged to. */
    namespace_id: LoonFS.NamespaceId;
}
