// This file was auto-generated by Fern from our API Definition.

/**
 * Object counts deleted by one garbage-collection pass, grouped by family.
 */
export interface DeletedObjectCounts {
    /** Released checkpoint records deleted after their grace window. */
    checkpoint_records: number;
    /** Content reclaimed through completed upload sessions. */
    content_objects: number;
    /** Unreferenced manifests deleted. */
    manifests: number;
    /** Unreferenced metadata segments deleted. */
    metadata_segments: number;
    /** Successful deletion attempts under a retired namespace owner prefix. */
    retired_content_objects: number;
    /** Upload-session control objects deleted after the reap window. */
    upload_sessions: number;
    /** Unreferenced WAL segments deleted. */
    wal_segments: number;
}
