// This file was auto-generated by Fern from our API Definition.

/**
 * Options for starting a direct multipart upload.
 */
export interface DirectMultipartUploadOptions {
    /**
     * Byte length of every part except the last, or `None` for the
     * server's default.
     *
     * Providers accept at most 10,000 parts, so this value also limits the
     * maximum upload size. Clients can request larger parts for large files.
     */
    part_size_bytes?: (number | null) | undefined;
}
