// This file was auto-generated by Fern from our API Definition.

/**
 * What a `direct_multipart` client asks for when it opens a session.
 *
 * A begin request declares no length and no digest: the session exists to
 * receive bytes whose length may not be known yet. All it settles is the
 * geometry the client cuts to.
 */
export interface DirectMultipartUploadOptions {
    /**
     * Byte length of every part except the last, or `None` for the
     * server's default.
     *
     * The value bounds the object: a provider accepts at most 10,000
     * parts, so this session can carry at most `part_size_bytes × 10_000`
     * bytes. A client that knows its payload is very large asks for a
     * larger part size; one that does not know its length at all takes the
     * default and keeps asking for part URLs until its stream ends.
     */
    part_size_bytes?: (number | null) | undefined;
}
