// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Part geometry returned for a direct multipart upload.
 *
 * The begin response does not include a content reference or part count
 * because the final payload is not known yet. The server owns the provider
 * upload id and returns the content reference only after completion.
 */
export interface DirectMultipartUpload {
    /**
     * Checksum algorithm every part and the complete assembled payload must
     * use for this session.
     */
    checksum_algorithm: LoonFS.ChecksumAlgorithm;
    /**
     * Byte length of every part except the last. At most 10,000 parts may
     * be uploaded, so this bounds the object at `part_size_bytes × 10_000`.
     */
    part_size_bytes: number;
}
