// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Presigned direct_put upload details. The raw object key is intentionally not public.
 */
export interface DirectPutUpload {
    /** Short-lived write capability the client uses without learning the raw object key. */
    access: LoonFS.ObjectTransferAccess;
    /**
     * Immutable object identity the server minted, plus the byte length and
     * checksum covered by the signed request. Completion and the later
     * commit both name exactly this reference.
     */
    content_ref: LoonFS.ContentRef;
}
