// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Add bytes to the end of a file inode as its next revision.
 */
export interface FilesystemOperationAppendFileByInode {
    /** The content revision that must still be current. */
    expected_revision_no?: LoonFS.RevisionNo | undefined;
    /** The bytes to add as base64, from 1 byte to 256 KiB. */
    inline_content: string;
    /** File to append to. */
    inode_id: LoonFS.InodeId;
}
