// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Restore an older revision as the current revision of a file inode.
 */
export interface FilesystemOperationRestoreRevisionByInode {
    /** Visible file to restore. */
    inode_id: LoonFS.InodeId;
    /** Existing historical revision whose content will be copied into a new current revision. */
    source_revision_no: LoonFS.RevisionNo;
}
