// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Add bytes to the end of a file as its next revision.
 */
export interface FilesystemOperationAppendFile {
    /** The inode that the path must still resolve to. */
    expected_inode_id?: LoonFS.InodeId | undefined;
    /** With an inode precondition, the content revision that must still be current. */
    expected_revision_no?: LoonFS.RevisionNo | undefined;
    /** The bytes to add as base64, from 1 byte to 256 KiB. */
    inline_content: string;
    /** Absolute path that must resolve to a visible file. */
    path: LoonFS.AbsolutePath;
}
