// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * One immutable file revision.
 */
export interface FileRevision {
    /** Commit ID for this revision. */
    commit_id: LoonFS.CommitId;
    /** The commit time in Unix milliseconds; `committed_seq` defines commit order. */
    committed_at_ms: number;
    /** Actor responsible for this revision, as supplied by the application. */
    committed_by: LoonFS.ActorId;
    /** Namespace sequence that created this revision. */
    committed_seq: LoonFS.ChangeSeq;
    /** Content stored for this revision. */
    content_ref: LoonFS.ContentRef;
    /** File inode that owns this revision. */
    inode_id: LoonFS.InodeId;
    /** Revision number within the file inode. */
    revision_no: LoonFS.RevisionNo;
}
