// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * An inode's attributes changed.
 */
export interface FilesystemChangeAttributesChanged {
    /**
     * The inode's complete attribute map after the update, so a consumer
     * projects it without reading anything back. An empty map is the
     * cleared state.
     */
    attributes: LoonFS.Attributes;
    /** New attribute revision for that inode. */
    attributes_revision_no: LoonFS.AttributeRevisionNo;
    /** Stable inode ID within a namespace */
    inode_id: string;
}
