// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Create a directory under an existing parent inode.
 */
export interface FilesystemOperationCreateDirectoryByInode {
    /** New directory name. */
    display_name: LoonFS.DisplayName;
    /** Parent directory. */
    parent_inode_id: LoonFS.InodeId;
}
