// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Move an inode if its current binding matches.
 */
export interface FilesystemOperationMoveByInode {
    /** Whether an existing destination file may be replaced. */
    behavior?: LoonFS.DestinationBehavior | undefined;
    /** Binding generation required for the move. */
    expected_binding_generation: string;
    /** Stable inode ID within a namespace */
    expected_destination_inode_id?: string | undefined;
    /** With `replace` behavior and an inode guard, the request requires this content revision. */
    expected_destination_revision_no?: LoonFS.RevisionNo | undefined;
    /** Stable inode ID within a namespace */
    inode_id: string;
    /** New name. */
    to_display_name: LoonFS.DisplayName;
    /** Stable inode ID within a namespace */
    to_parent_inode_id: string;
}
