// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * A file received a new current revision from a put or revision restore.
 */
export interface FilesystemChangeContentChanged {
    /** Immutable content published by the revision. */
    content_ref: LoonFS.ContentRef;
    /** File inode whose history advanced. */
    inode_id: LoonFS.InodeId;
    /** New monotonic position in that file's revision history. */
    revision_no: LoonFS.RevisionNo;
}
