// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Create one directory.
 */
export interface FilesystemOperationCreateDirectory {
    /**
     * Whether to create missing ancestor directories while requiring the final
     * component to be new.
     */
    parents?: boolean | undefined;
    /** Absolute destination path, rejected when invalid or already bound. */
    path: LoonFS.AbsolutePath;
}
