// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * One path-oriented filesystem operation.
 *
 * Unknown fields are rejected because concurrency guards are optional. A
 * misspelled guard must fail decoding instead of silently becoming `None`
 * and allowing an unguarded write. Any future fieldless variant must use
 * empty braces so serde also rejects unexpected fields for that variant.
 */
export type FilesystemOperation =
    | LoonFS.FilesystemOperation.CreateDirectory
    | LoonFS.FilesystemOperation.PutFile
    | LoonFS.FilesystemOperation.DeletePath
    | LoonFS.FilesystemOperation.MovePath
    | LoonFS.FilesystemOperation.CopyPath
    | LoonFS.FilesystemOperation.Undelete
    | LoonFS.FilesystemOperation.RestoreRevision
    | LoonFS.FilesystemOperation.UpdateAttributes;

export namespace FilesystemOperation {
    export interface CreateDirectory extends LoonFS.FsOpCreateDirectory {
        kind: "create_directory";
    }

    export interface PutFile extends LoonFS.FsOpPutFile {
        kind: "put_file";
    }

    export interface DeletePath extends LoonFS.FsOpDeletePath {
        kind: "delete_path";
    }

    export interface MovePath extends LoonFS.FsOpMovePath {
        kind: "move_path";
    }

    export interface CopyPath extends LoonFS.FsOpCopyPath {
        kind: "copy_path";
    }

    export interface Undelete extends LoonFS.FsOpUndelete {
        kind: "undelete";
    }

    export interface RestoreRevision extends LoonFS.FsOpRestoreRevision {
        kind: "restore_revision";
    }

    export interface UpdateAttributes extends LoonFS.FsOpUpdateAttributes {
        kind: "update_attributes";
    }
}
