// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Move one path to another path.
 */
export interface FilesystemOperationMovePath {
    /** Whether an existing destination file may be replaced. */
    behavior?: LoonFS.DestinationBehavior | undefined;
    /** With `replace` behavior, the destination inode required by the request. */
    expected_destination_inode_id?: LoonFS.InodeId | undefined;
    /** With `replace` behavior and an inode guard, the required content revision. */
    expected_destination_revision_no?: LoonFS.RevisionNo | undefined;
    /** Absolute source path that must resolve to a visible inode. */
    from_path: LoonFS.AbsolutePath;
    /** Absolute destination whose parent must be visible and writable. */
    to_path: LoonFS.AbsolutePath;
}
