// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * One immutable file revision.
 */
export interface FileRevision {
    /** Commit ID for this revision. */
    commit_id: LoonFS.CommitId;
    /**
     * Wall-clock stamp of the commit that created this revision, in Unix
     * milliseconds. Observational: `committed_seq` is the order.
     */
    committed_at_ms: number;
    /** Actor responsible for this revision, as supplied by the application. */
    committed_by: LoonFS.ActorRef;
    /** Namespace sequence that created this revision. */
    committed_seq: LoonFS.ChangeSeq;
    /** Content stored for this revision. */
    content_ref: LoonFS.ContentRef;
    /** Stable inode ID within a namespace */
    inode_id: string;
    /** Revision number within the file inode. */
    revision_no: LoonFS.RevisionNo;
}
