// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Create or replace one file with an already-durable content ref.
 */
export interface FilesystemOperationPutFile {
    /** Whether an existing file may receive a new revision instead of causing a conflict. */
    behavior?: LoonFS.DestinationBehavior | undefined;
    /** Immutable bytes that must be covered by a valid preparation proof. */
    content_ref: LoonFS.ContentRef;
    /** With `replace` behavior, the request requires the path to contain this inode. */
    expected_inode_id?: LoonFS.InodeId | undefined;
    /** With `replace` behavior and an inode precondition, the request requires this content revision. */
    expected_revision_no?: LoonFS.RevisionNo | undefined;
    /** Absolute destination path; missing ancestors are created automatically. */
    path: LoonFS.AbsolutePath;
}
