// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Write and remove attributes on the inode one path resolves to.
 */
export interface FilesystemOperationUpdateAttributes {
    /** With an inode precondition, the attribute revision that must still be current. */
    expected_attributes_revision_no?: LoonFS.AttributeRevisionNo | undefined;
    /** The inode that the path must still resolve to before the update. */
    expected_inode_id?: LoonFS.InodeId | undefined;
    /** Absolute path that must resolve to a visible file or directory. */
    path: LoonFS.AbsolutePath;
    /** The attribute keys to remove, including duplicates that validation must reject. */
    remove?: LoonFS.AttributeKey[] | undefined;
    /**
     * The attributes to write, replacing values for matching keys and leaving
     * other keys unchanged.
     */
    set?: Record<string, LoonFS.AttributeValue> | undefined;
}
