// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * A file or directory subtree was deleted. Use the enclosing change's
 * `committed_seq` as `deletion_seq` when restoring it.
 */
export interface FilesystemChangeDeleted {
    /**
     * Directory binding removed by the deletion, when the delete
     * recorded one.
     */
    deleted_direntry?: LoonFS.DeletedDirentry | undefined;
    /** Stable inode ID within a namespace */
    inode_id: string;
}
