// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Move one path to another path.
 */
export interface FilesystemOperationMovePath {
    /** Whether an existing destination file may be replaced. */
    behavior?: LoonFS.DestinationBehavior | undefined;
    /** Stable inode ID within a namespace */
    destination_expected_inode_id?: string | undefined;
    /**
     * When set (with `replace` behavior), the replacement applies only
     * while the destination still holds this revision.
     */
    destination_expected_revision_no?: LoonFS.RevisionNo | undefined;
    /** Absolute source path that must resolve to a visible inode. */
    from_path: LoonFS.AbsolutePath;
    /** Absolute destination whose parent must be visible and writable. */
    to_path: LoonFS.AbsolutePath;
}
