// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Delete an inode if its current binding matches.
 */
export interface FilesystemOperationDeleteByInode {
    /** Whether a non-empty directory may be tombstoned recursively. */
    behavior?: LoonFS.DeleteDirectoryBehavior | undefined;
    /** Binding generation required for the delete. */
    expected_binding_generation: string;
    /** Stable inode ID within a namespace */
    inode_id: string;
}
