// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Copy one file path to another path.
 */
export interface FilesystemOperationCopyPath {
    /** Whether an existing destination file may receive a copied revision. */
    behavior?: LoonFS.DestinationBehavior | undefined;
    /** Absolute source path that must resolve to a visible file. */
    from_path: LoonFS.AbsolutePath;
    /** Absolute destination whose parent must be visible and writable. */
    to_path: LoonFS.AbsolutePath;
}
