// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * A directory was created.
 */
export interface FilesystemChangeDirectoryCreated {
    /** User-facing spelling of the new entry. */
    display_name: LoonFS.DisplayName;
    /** Stable inode ID within a namespace */
    inode_id: string;
    /** Stable inode ID within a namespace */
    parent_inode_id: string;
}
