// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Result of one mark-and-sweep garbage-collection pass.
 *
 * Deletion counts are grouped by object family. Checkpoint releases and
 * retained candidates are grouped by reason.
 */
export interface GcResponse {
    /**
     * True when the pass reached `max_objects` before it finished. Use
     * `next_cursor` to continue or run again with a larger limit.
     */
    budget_exhausted: boolean;
    /**
     * True when `max_objects` was too small to build the complete reference
     * set required for completed-content reclamation.
     */
    content_reclamation_deferred: boolean;
    /** Objects the pass deleted, split by object family. */
    deleted: LoonFS.DeletedObjectCounts;
    /** Namespace the pass ran against. */
    namespace_id: LoonFS.NamespaceId;
    /**
     * Opaque resume token when more candidates remain. It is valid only for
     * the same namespace.
     */
    next_cursor?: string | undefined;
    /**
     * Earliest known time when a retained upload session may become
     * reclaimable. This covers open-session leases and grace periods for
     * aborted or completed sessions. It only reflects candidates inspected
     * by this pass, so absence does not mean no future work remains.
     */
    next_reclamation_at_ms?: number | undefined;
    /**
     * Checkpoint records the pass released, split by the reason each one
     * was released.
     */
    released_checkpoints: LoonFS.ReleasedCheckpointCounts;
    /** `retained_candidates` grouped by reason. */
    retained: LoonFS.RetainedCandidates;
    /**
     * Candidates retained at delete time (grace window, missing
     * timestamps, or reachable from the fresh root set).
     */
    retained_candidates: number;
    /** True when ambiguous roots suppressed manifest/segment deletion. */
    retention_degraded: boolean;
}
