// This file was auto-generated by Fern from our API Definition.

/**
 * Optional overrides for one garbage-collection pass. Absent fields use
 * the server's conservative defaults.
 *
 * Every field is optional, so a typo would take the default instead of the
 * override the caller asked for. Unknown fields are rejected so a misspelled
 * `max_objects` fails loudly rather than running an unbounded pass.
 */
export interface GcRequest {
    /**
     * Opaque resume token returned as `next_cursor` by an earlier pass
     * against the same namespace.
     */
    cursor?: (string | null) | undefined;
    /**
     * Objects younger than this are never deleted, reachable or not. The
     * window has a derived safety floor (publication budgets plus provider
     * deadlines); a smaller value is rejected as `invalid_request`.
     */
    grace_window_ms?: (number | null) | undefined;
    /**
     * Maximum objects this invocation may read or decide. Omit to retain
     * the run-to-completion behavior.
     *
     * A completed upload session past its reclamation grace makes the pass
     * read every live manifest and retained WAL segment to find out
     * whether anything still references its content, and that read is
     * charged here like any other. A budget too small to finish it does
     * not stall the pass: the session is retained, the response sets
     * `content_reclamation_deferred`, and the sweep carries on through
     * everything else. What a chronically small budget costs is content
     * left unreclaimed, not progress. Give a pass at least as many objects
     * as the namespace has live manifests and retained segments for that
     * content to come back.
     */
    max_objects?: (number | null) | undefined;
}
