// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * One content-search request.
 *
 * Every field but `pattern` is optional, and each one selects results. A
 * misspelled `case_insensitive` or `path_prefix` would decode to the default
 * and answer a different search than the caller asked for, with no sign that
 * anything was dropped, so unknown fields are rejected.
 */
export interface GrepRequest {
    /**
     * Permit a capped exhaustive scan when the pattern yields no required
     * grams. Refused beyond the server's scan budget.
     */
    allow_scan?: boolean | undefined;
    /**
     * When the unindexed tail exceeds the scan budget, return
     * indexed-only results (reported via `tail_scanned: false`) instead
     * of failing with `index_lagging`.
     */
    allow_stale?: boolean | undefined;
    /**
     * Match case-insensitively. Verification is exact; the index remains
     * consulted through its case-folded grams.
     */
    case_insensitive?: boolean | undefined;
    /**
     * Resume cursor from a previous page. The cursor resumes strictly
     * after the last candidate the issuing page finished scanning and is
     * bound to that page's request; each page is evaluated against the
     * namespace head at page time.
     */
    cursor?: (string | null) | undefined;
    /** Maximum matches per page. */
    limit?: (number | null) | undefined;
    /**
     * Restrict matches to files under this complete absolute path, resolved
     * to a directory inode before candidates are filtered.
     */
    path_prefix?: LoonFS.AbsolutePath | undefined;
    /**
     * The pattern, in the Rust `regex` crate's dialect (no backreferences
     * or lookaround). Its UTF-8 encoding must be at most 1024 bytes.
     * Patterns that require no literal bytes are rejected with
     * `query_unindexable` unless `allow_scan` is set.
     */
    pattern: string;
}
