// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * The namespace's grep-index lifecycle and its cheap bookkeeping (admin
 * plane).
 */
export type GrepIndex = LoonFS.GrepIndex.Disabled | LoonFS.GrepIndex.Backfilling | LoonFS.GrepIndex.Active;

export namespace GrepIndex {
    export interface Disabled extends LoonFS.GrepIndexLifecycleDisabled {
        status: "disabled";
    }

    export interface Backfilling extends LoonFS.GrepIndexLifecycleBackfilling {
        status: "backfilling";
    }

    export interface Active extends LoonFS.GrepIndexLifecycleActive {
        status: "active";
    }
}
