// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * The initial walk over a pinned checkpoint is running. Nothing is
 * searchable yet.
 */
export interface GrepIndexLifecycleBackfilling {
    /** Checkpoint pinning the state being walked. */
    checkpoint_id: LoonFS.CheckpointId;
    /** Stable inode ID within a namespace */
    cursor_inode_id?: string | undefined;
    /**
     * Namespace sequence the pinned checkpoint captured. Reaching it
     * is what completes the backfill.
     */
    target_seq: LoonFS.ChangeSeq;
    /** Namespace the status describes. */
    namespace_id: LoonFS.NamespaceId;
    /** Run number the index allocates next. */
    next_run_no: LoonFS.RunNo;
    /** True while a partitioned segment reorganization is in progress. */
    reorganize_pending: boolean;
}
