// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * The index follows the change feed. Commits at or below the watermark
 * are searchable.
 */
export interface GrepIndexLifecycleActive {
    /** Sequence of the commit at the index cursor. */
    built_through_seq: LoonFS.ChangeSeq;
    /**
     * Offset of the next change event within `built_through_seq`, or
     * zero when the whole commit is represented.
     */
    next_event_index?: number | undefined;
}
