// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * The maintenance status of a namespace's grep index.
 */
export type GrepIndex = LoonFS.GrepIndex.Active | LoonFS.GrepIndex.Backfilling | LoonFS.GrepIndex.Disabled;

export namespace GrepIndex {
    export interface Active extends LoonFS.GrepIndexLifecycleActive {
        status: "active";
    }

    export interface Backfilling extends LoonFS.GrepIndexLifecycleBackfilling {
        status: "backfilling";
    }

    export interface Disabled extends LoonFS.GrepIndexLifecycleDisabled {
        status: "disabled";
    }
}
