// This file was auto-generated by Fern from our API Definition.

/**
 * One explicit grep index garbage-collection pass (maintenance API group).
 */
export type GrepGcRequest = Record<string, unknown>;
