// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * An index following the change feed through its searchable watermark.
 */
export interface GrepIndexLifecycleActive {
    /** Sequence of the commit at the index cursor. */
    built_through_seq: LoonFS.ChangeSeq;
    /** Namespace the status describes. */
    namespace_id: LoonFS.NamespaceId;
    /**
     * The next change-event offset within `built_through_seq`, or zero when the
     * whole commit is indexed.
     */
    next_event_index?: number | undefined;
    /** Run number the index allocates next. */
    next_run_no: LoonFS.RunNo;
    /** True while a partitioned segment reorganization is in progress. */
    reorganize_pending: boolean;
}
