// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * The namespace's grep-index lifecycle and its cheap bookkeeping (admin
 * plane).
 */
export interface GrepIndexStatusResponse {
    /** Namespace the status describes. */
    namespace_id: LoonFS.NamespaceId;
    /** Next logical run ordinal the index will allocate. */
    next_run_ordinal: number;
    /** True while a partitioned segment reorganization is in progress. */
    reorganize_pending: boolean;
}
