// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Result of one explicit grep index garbage-collection pass (maintenance API group).
 */
export interface GrepGcResponse {
    /** Other unreferenced grep objects deleted after the grace window. */
    deleted_other_objects: number;
    /** Unreferenced grep segments older than the minimum segment age. */
    deleted_segments: number;
    /** Namespace whose grep-owned keyspace was inspected. */
    namespace_id: LoonFS.NamespaceId;
    /** Whether an absent or tombstoned namespace had extension state reaped. */
    namespace_reaped: boolean;
    /** Referenced, young, or unrecognized candidates retained by the pass. */
    retained_candidates: number;
}
