// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * No index is maintained for this namespace.
 */
export interface GrepIndexLifecycleDisabled {
    /** Namespace the status describes. */
    namespace_id: LoonFS.NamespaceId;
    /** Run number the index allocates next. */
    next_run_no: LoonFS.RunNo;
    /** True while a partitioned segment reorganization is in progress. */
    reorganize_pending: boolean;
}
