// This file was auto-generated by Fern from our API Definition.

/** Filesystem item kind. */
export const InodeKind = {
    File: "file",
    Dir: "dir",
} as const;
export type InodeKind = (typeof InodeKind)[keyof typeof InodeKind];
