// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * One page of active checkpoint records.
 */
export interface ListCheckpointsResponse {
    /**
     * Active records in ascending checkpoint-id order. Released records are
     * omitted even if garbage collection has not deleted them yet.
     */
    checkpoints: LoonFS.Checkpoint[];
    /** Namespace the records belong to. */
    namespace_id: LoonFS.NamespaceId;
    /** Opaque cursor for the next page. */
    next_cursor?: (string | null) | undefined;
}
