// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * One directory listing and the namespace head used to read it.
 */
export interface ListPathEntriesResponse {
    /** The directory entries in canonical name-key order. */
    entries: LoonFS.PathEntry[];
    /** Namespace head sequence this listing was read from. */
    head_seq: LoonFS.ChangeSeq;
    /** Namespace that was read. */
    namespace_id: LoonFS.NamespaceId;
    /** Cursor for the next page, if more entries remain. */
    next_cursor?: string | undefined;
    /** Absolute path of the listed directory. */
    path: LoonFS.AbsolutePath;
}
