// This file was auto-generated by Fern from our API Definition.

/**
 * Version number for a namespace manifest. It can increase when metadata changes, even if no namespace commit is written.
 */
export type ManifestId = number;
