// This file was auto-generated by Fern from our API Definition.

/**
 * Overrides for the metadata-upkeep action.
 */
export interface MetadataMaintenanceRequest {
    /**
     * Flush the visible WAL tail once it reaches this many segments.
     * Absent uses the server's default threshold; zero, and any value above
     * the write-rejection threshold, are rejected as `invalid_request`.
     */
    max_wal_tail_segments?: (number | null) | undefined;
}
