// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * The outcome of one metadata compaction run.
 */
export type MetadataCompactionOutcome =
    | LoonFS.MetadataCompactionOutcome.Abandoned
    | LoonFS.MetadataCompactionOutcome.BoundedMergePublished
    | LoonFS.MetadataCompactionOutcome.Cancelled
    | LoonFS.MetadataCompactionOutcome.Fenced
    | LoonFS.MetadataCompactionOutcome.NotNeeded
    | LoonFS.MetadataCompactionOutcome.Published;

export namespace MetadataCompactionOutcome {
    export interface Abandoned extends LoonFS.MetadataCompactionOutcomeAbandoned {
        outcome: "abandoned";
    }

    export interface BoundedMergePublished extends LoonFS.MetadataCompactionOutcomeBoundedMergePublished {
        outcome: "bounded_merge_published";
    }

    export interface Cancelled extends LoonFS.MetadataCompactionOutcomeCancelled {
        outcome: "cancelled";
    }

    export interface Fenced extends LoonFS.MetadataCompactionOutcomeFenced {
        outcome: "fenced";
    }

    export interface NotNeeded extends LoonFS.MetadataCompactionOutcomeNotNeeded {
        outcome: "not_needed";
    }

    export interface Published extends LoonFS.MetadataCompactionOutcomePublished {
        outcome: "published";
    }
}
