// This file was auto-generated by Fern from our API Definition.

/**
 * Another process claimed the namespace compactor role; nothing was published.
 */
export type MetadataCompactionOutcomeFenced = {};
