// This file was auto-generated by Fern from our API Definition.

/**
 * The selected window fit a bounded step and this run published it.
 */
export type MetadataCompactionOutcomeBoundedMergePublished = {};
