// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * What one metadata-upkeep action did, part by part.
 */
export interface MetadataMaintenanceResponse {
    /** What the reorganization unit did. */
    reorganize: LoonFS.ReorganizeStepOutcome;
    /** What the WAL flush did. */
    wal_flush: LoonFS.WalFlushStepOutcome;
}
