// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * The selected run window was replaced in a published manifest.
 */
export interface MetadataCompactionOutcomePublished {
    /** Input bytes read by the compaction. */
    input_bytes: number;
    /** Manifest published by the compaction. */
    manifest_no: LoonFS.ManifestNo;
    /** Output bytes written by the compaction. */
    output_bytes: number;
    /** Output segments written by the compaction. */
    output_segments: number;
    /** Rows read by the compaction. */
    rows_read: number;
    /** Rows written by the compaction. */
    rows_written: number;
}
