// This file was auto-generated by Fern from our API Definition.

/**
 * Durable id for one namespace.
 *
 * A namespace id names successive filesystem generations. This id is not a display name.
 * Its serialized form is 1 to 128
 * lowercase ASCII letters, digits, dots, underscores, or hyphens, starting
 * with a letter or digit; the `loonfs-` prefix is reserved for system use.
 */
export type NamespaceId = string;
