// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Access rows govern every operation.
 */
export interface NamespaceAccessAcl {
    /** Identity domain the namespace's principal ids belong to. */
    principal_scope: LoonFS.PrincipalScope;
    /**
     * The root inode's grants at genesis, normally `admin` for each
     * initial administrator.
     */
    root_grants: LoonFS.AccessGrants;
}
