// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Current state for one namespace.
 */
export interface Namespace {
    /** Current visible namespace sequence. */
    head_seq: LoonFS.ChangeSeq;
    /** Namespace ID. */
    namespace_id: LoonFS.NamespaceId;
    /** Oldest sequence still promised for incremental replay. */
    retention_floor_seq: LoonFS.ChangeSeq;
}
