// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * The source a forked namespace started from.
 */
export interface NamespaceForkBasis {
    /** Source sequence the fork captured. */
    source_head_seq: LoonFS.ChangeSeq;
    /** Namespace the fork was taken from. */
    source_namespace_id: LoonFS.NamespaceId;
}
