// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Namespace state and storage details used by maintenance.
 */
export interface NamespaceDiagnostics {
    /** Current manifest pointer recorded by the head. */
    current_manifest_no?: LoonFS.ManifestNo | undefined;
    /** Current visible namespace sequence. */
    head_seq: LoonFS.ChangeSeq;
    /** Namespace ID. */
    namespace_id: LoonFS.NamespaceId;
    /** Oldest sequence still promised for incremental replay. */
    retention_floor_seq: LoonFS.ChangeSeq;
    /** Number of visible WAL segments after the current manifest. */
    wal_tail_segments: number;
}
