// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Access rows govern operations in this identity domain.
 */
export interface NamespaceAccessModeAcl {
    /** Identity domain the namespace's principal ids belong to. */
    principal_scope: LoonFS.PrincipalScope;
}
