// This file was auto-generated by Fern from our API Definition.

/**
 * Which generation of its id a namespace is. A newly created namespace is generation 1; each recreation after a deletion increments it.
 */
export type NamespaceGeneration = number;
