// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * A namespace's access mode as reported, without its genesis grants.
 */
export type NamespaceAccessMode = LoonFS.NamespaceAccessMode.Acl | LoonFS.NamespaceAccessMode.Unrestricted;

export namespace NamespaceAccessMode {
    export interface Acl extends LoonFS.NamespaceAccessModeAcl {
        kind: "acl";
    }

    export interface Unrestricted extends LoonFS.NamespaceAccessModeUnrestricted {
        kind: "unrestricted";
    }
}
