// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Namespace state and storage details used by maintenance.
 */
export interface NamespaceDiagnostics {
    /** Time the namespace was created, in Unix milliseconds. */
    created_at_ms: number;
    /** Actor that created the namespace, as supplied by the application. */
    created_by: LoonFS.ActorId;
    /** The namespace's current manifest number. */
    current_manifest_no?: LoonFS.ManifestNo | undefined;
    /** Present only for a fork: the source it was forked from. */
    fork_basis?: LoonFS.NamespaceForkBasis | undefined;
    /** Which generation of its id this namespace is. Recreating a deleted id increments it. */
    generation: LoonFS.NamespaceGeneration;
    /** Current visible namespace sequence. */
    head_seq: LoonFS.ChangeSeq;
    /** Number of active user checkpoints, including expired records awaiting collection. */
    live_checkpoints: number;
    /** Number of snapshots that had not expired when diagnostics began. */
    live_snapshots: number;
    /** Namespace ID. */
    namespace_id: LoonFS.NamespaceId;
    /** Oldest sequence still promised for incremental replay. */
    retention_floor_seq: LoonFS.ChangeSeq;
    /** Number of visible WAL segments after the current manifest. */
    wal_tail_segments: number;
}
