// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Current state for one namespace.
 */
export interface Namespace {
    /** The namespace's access mode. */
    access: LoonFS.NamespaceAccessMode;
    /** Time the namespace was created, in Unix milliseconds. */
    created_at_ms: number;
    /** Actor that created the namespace, as supplied by the application. */
    created_by: LoonFS.ActorId;
    /** Present only for a fork: the source it was forked from. */
    fork_basis?: LoonFS.NamespaceForkBasis | undefined;
    /** Which generation of its id this namespace is. Recreating a deleted id increments it. */
    generation: LoonFS.NamespaceGeneration;
    /** Current visible namespace sequence. */
    head_seq: LoonFS.ChangeSeq;
    /** Namespace ID. */
    namespace_id: LoonFS.NamespaceId;
    /** Oldest sequence still promised for incremental replay. */
    retention_floor_seq: LoonFS.ChangeSeq;
}
