// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * A directory, which has no revision payload in v0.
 *
 * The entry tag reuses [`InodeKind`]'s wire vocabulary.
 */
export interface PathEntryDirectory {
    /**
     * The complete attribute map at `attributes_revision_no`.
     *
     * An inode that has never had attributes written is at revision 0 with
     * an empty map.
     */
    attributes?: LoonFS.Attributes | undefined;
    /** The attribute revision this projection represents. */
    attributes_revision_no?: LoonFS.AttributeRevisionNo | undefined;
    /**
     * Time of the latest attribute update, in Unix milliseconds. This is
     * `None` for the initial empty state at revision 0.
     */
    attributes_updated_at_ms?: number | undefined;
    /**
     * Actor responsible for the latest attribute update. This is `None` for
     * the initial empty state at revision 0.
     */
    attributes_updated_by?: LoonFS.ActorRef | undefined;
    /** Opaque identifier for this entry's current parent/name binding. Absent for the namespace root. */
    binding_generation?: string | undefined;
    /**
     * Time the inode was created, in Unix milliseconds. Sequence numbers
     * determine order.
     */
    created_at_ms: number;
    /** Actor that created this inode, as supplied by the application. */
    created_by: LoonFS.ActorRef;
    /** Stored display name for this path component, absent for the nameless root. */
    display_name?: LoonFS.DisplayName | undefined;
    /** Namespace head sequence this answer was read from. */
    head_seq: LoonFS.ChangeSeq;
    /** Stable inode ID within a namespace */
    inode_id: string;
    /** Namespace that was read. */
    namespace_id: LoonFS.NamespaceId;
    /** Stable inode ID within a namespace */
    parent_inode_id?: string | undefined;
    /** Absolute path as rendered from stored display names. */
    path: LoonFS.AbsolutePath;
}
