// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Metadata for one path returned by stat and directory-listing operations.
 *
 * File entries include the current revision and content details. Directory
 * entries do not. Attribute fields are included only when requested and are
 * serialized at the top level of the entry. Callers can pass
 * `attributes_revision_no` as `expected_attributes_revision_no` when updating
 * attributes.
 */
export type PathEntry = LoonFS.PathEntry.Dir | LoonFS.PathEntry.File;

export namespace PathEntry {
    export interface Dir extends LoonFS.PathEntryDirectory {
        inode_kind: "dir";
    }

    export interface File extends LoonFS.PathEntryFile {
        inode_kind: "file";
    }
}
