// This file was auto-generated by Fern from our API Definition.

/**
 * Opaque identity-domain id containing 1 to 256 visible ASCII characters other than the comma.
 */
export type PrincipalScope = string;
