// This file was auto-generated by Fern from our API Definition.

/**
 * Checkpoint records released by one GC pass, grouped by reason.
 *
 * Releasing a record stops it from pinning data. A later pass may delete the
 * record after its grace window and count that under
 * [`DeletedObjectCounts::checkpoint_records`].
 */
export interface ReleasedCheckpointCounts {
    /**
     * User-owned records released because their expiry passed, or because
     * they sit on a terminally deleted namespace.
     */
    expired: number;
    /**
     * Fork-owned records released because their target namespace is
     * provably gone.
     */
    fork: number;
    /**
     * Active records released because their basis manifest is verifiably
     * gone.
     */
    missing_basis: number;
    /**
     * Snapshot-owned records released because their expiry passed, or
     * because they sit on a terminally deleted namespace.
     */
    snapshot: number;
}
