// This file was auto-generated by Fern from our API Definition.

/**
 * Checkpoint record counts released by one garbage-collection pass, grouped by reason.
 */
export interface ReleasedCheckpointCounts {
    /** User-owned records released after expiry or terminal namespace deletion. */
    expired: number;
    /** Fork-owned records released because their target namespaces are gone. */
    fork: number;
    /** Active records released because their basis manifests are gone. */
    missing_basis: number;
    /** Snapshot-owned records released after expiry or terminal namespace deletion. */
    snapshot: number;
}
