// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Result of releasing a checkpoint pin.
 */
export interface ReleaseCheckpointResponse {
    /** Checkpoint the release targeted. */
    checkpoint_id: LoonFS.CheckpointId;
    /** Namespace the checkpoint belonged to. */
    namespace_id: LoonFS.NamespaceId;
}
