// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * The outcome of the metadata-reorganization part of a maintenance pass.
 */
export type ReorganizeStepOutcome =
    | LoonFS.ReorganizeStepOutcome.CompactionRequired
    | LoonFS.ReorganizeStepOutcome.NotNeeded
    | LoonFS.ReorganizeStepOutcome.RootAdvanced
    | LoonFS.ReorganizeStepOutcome.UnitPublished;

export namespace ReorganizeStepOutcome {
    export interface CompactionRequired extends LoonFS.ReorganizeStepOutcomeCompactionRequired {
        outcome: "compaction_required";
    }

    export interface NotNeeded extends LoonFS.ReorganizeStepOutcomeNotNeeded {
        outcome: "not_needed";
    }

    export interface RootAdvanced extends LoonFS.ReorganizeStepOutcomeRootAdvanced {
        outcome: "root_advanced";
    }

    export interface UnitPublished extends LoonFS.ReorganizeStepOutcomeUnitPublished {
        outcome: "unit_published";
    }
}
