// This file was auto-generated by Fern from our API Definition.

/**
 * A family group needs a streaming compaction. Run the `metadata_compaction` job.
 */
export type ReorganizeStepOutcomeCompactionRequired = {};
