// This file was auto-generated by Fern from our API Definition.

/**
 * Why a pass kept what it kept: `retained_candidates` split by the
 * decision that spared each candidate.
 *
 * The reasons are a closed set — one per place the sweep decides against
 * deleting — so every field is always reported, and a zero is the answer
 * that nothing was kept for that reason. The counts sum to
 * `retained_candidates`.
 *
 * Retention is a decision per candidate examined, not per object in the
 * namespace: one object examined by two passes is counted by each.
 */
export interface RetainedCandidates {
    /**
     * A checkpoint record this pass could have advanced but could not
     * prove ready: a lost compare-and-swap, an unreadable record, a fork
     * target not provably gone, a released record still inside its grace
     * window, or an active pin that is simply doing its job. The pins
     * themselves are listed by
     * `GET /v0/admin/namespaces/{ns}/checkpoints`.
     */
    checkpoint_not_releasable: number;
    /**
     * A completed session whose content reclamation was skipped because
     * the reference scan did not fit in `max_objects`
     * (`content_reclamation_deferred` is set too).
     */
    content_scan_deferred: number;
    /**
     * Root resolution failed somewhere in this pass, so manifest and table
     * deletion was suppressed wholesale (`degraded_retention` is set too).
     */
    degraded_roots: number;
    /**
     * Unreachable, but younger than the grace window by the object's own
     * provider timestamp. A later pass deletes it.
     */
    grace_window: number;
    /**
     * Unreachable, and the provider reported no last-modified time at all,
     * so the object's age is unknown and it is treated as young.
     */
    no_provider_timestamp: number;
    /**
     * Unreachable, but this namespace published no manifest old enough to
     * say what it referenced when the grace window opened, so nothing
     * proves the object was already unreferenced then. A reader that pinned
     * its anchor inside the window may still be reading it, and the pass
     * keeps it until a manifest ages past the window.
     */
    no_reference_manifest: number;
    /**
     * Selected as unreachable, then found reachable by the re-verification
     * that runs immediately before every deletion. A candidate the pass
     * already knew was reachable is never examined at all, so this counts
     * the namespace moving underneath the pass rather than the size of its
     * live set.
     */
    referenced: number;
    /**
     * A key under a swept family that this collector does not recognize as
     * one of its own. Never deleted, whatever its age.
     */
    unrecognized_key: number;
    /**
     * An upload session held over for a reason no clock resolves: a lost
     * compare-and-swap, a record that vanished mid-pass, or a reference
     * set this pass could not establish. Only a later pass answers it.
     */
    upload_session_undecided: number;
    /**
     * An upload session waiting out a window a clock resolves: an open
     * session's lease plus the grace, an aborted session's grace, or a
     * completed session's derived content-reclamation grace.
     * `next_reclamation_at_ms` reports the soonest of these.
     */
    upload_session_window: number;
}
