// This file was auto-generated by Fern from our API Definition.

/**
 * Candidates inspected but not deleted by one GC pass.
 *
 * Every field is present, including zero counts. The fields sum to
 * `retained_candidates` in [`GcResponse`].
 *
 * An object inspected by multiple passes is counted once per pass.
 */
export interface RetainedCandidates {
    /** Checkpoint records that could not be safely released or deleted. */
    checkpoint_not_releasable: number;
    /**
     * Completed sessions skipped because the reference scan exceeded
     * `max_objects`. The response also sets `content_reclamation_deferred`.
     */
    content_scan_deferred: number;
    /**
     * Candidates kept because root resolution failed. The response also
     * sets `retention_degraded`.
     */
    degraded_roots: number;
    /**
     * Unreachable candidates with no provider timestamp. Their age is
     * unknown, so the pass keeps them.
     */
    no_provider_timestamp: number;
    /**
     * Unreachable candidates that cannot be checked against a manifest old
     * enough to cover the grace window.
     */
    no_reference_manifest: number;
    /** Candidates found reachable during the final check before deletion. */
    referenced: number;
    /**
     * Unrecognized keys in a family scanned by GC. These keys are never
     * deleted.
     */
    unrecognized_key: number;
    /**
     * Upload sessions kept because the pass could not determine whether
     * they were safe to delete.
     */
    upload_session_undecided: number;
    /** Upload sessions still protected by a lease or grace window. */
    upload_session_window: number;
    /**
     * Unreachable, but younger than the grace window by the object's own
     * provider timestamp. A later pass deletes it.
     */
    within_grace_window: number;
}
