// This file was auto-generated by Fern from our API Definition.

/**
 * The candidates inspected but not deleted by one garbage-collection pass.
 *
 * Every field is present and contributes to [`GcResponse::retained_candidates`].
 */
export interface RetainedCandidates {
    /** Checkpoint records that could not be safely released or deleted. */
    checkpoint_not_releasable: number;
    /** Unreachable candidates without provider timestamps. */
    no_provider_timestamp: number;
    /** Candidates protected by current references or manifest discovery. */
    referenced: number;
    /** Unrecognized keys retained from object families scanned by garbage collection. */
    unrecognized_key: number;
    /** Upload sessions whose deletion safety could not be determined. */
    upload_session_undecided: number;
    /** Upload sessions still protected by a lease or grace window. */
    upload_session_window: number;
    /** Unreachable candidates younger than the grace window by their provider timestamps. */
    within_grace_window: number;
}
