// This file was auto-generated by Fern from our API Definition.

/**
 * Runs one bounded mark-and-sweep garbage-collection pass.
 */
export interface RunMaintenanceRequestGc {
    /**
     * The opaque `next_cursor` returned by an earlier call for this namespace.
     * Omitting it joins any active run; scan positions remain server-owned.
     */
    cursor?: (string | null) | undefined;
    /**
     * The minimum object age for deletion in milliseconds, which must meet the
     * server's advertised safety floor.
     */
    grace_window_ms?: (number | null) | undefined;
    /**
     * Maximum durable GC work steps in this call; the default is 1024.
     * Even a budget of one saves progress through marking and sweeping.
     * This is not a limit on object-store requests or memory.
     */
    max_steps?: (number | null) | undefined;
}
