// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Counts and deadlines from one collection call.
 */
export interface RunMaintenanceResponseGc {
    /** Objects the pass deleted, split by object family. */
    deleted: LoonFS.DeletedObjectCounts;
    /** The checkpoint records deleted by the pass, grouped by owner. */
    deleted_checkpoints_by_owner: LoonFS.DeletedCheckpointsByOwner;
    /** Namespace the pass ran against. */
    namespace_id: LoonFS.NamespaceId;
    /** The earliest pending generation deadline or future upload cleanup time. */
    next_reclamation_at_ms?: number | undefined;
    /** The current tombstone's deletion time plus the configured retirement grace. */
    reclaim_after_ms?: number | undefined;
    /** Candidates retained at deletion time, grouped by reason. */
    retained: LoonFS.RetainedCandidates;
}
