// This file was auto-generated by Fern from our API Definition.

/**
 * Collects aged, unreferenced objects.
 */
export interface RunMaintenanceRequestGc {
    /**
     * The minimum object age for deletion in milliseconds, which must meet the
     * server's advertised safety floor.
     */
    grace_window_ms?: number | undefined;
}
