// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * The committed administrator recovery.
 */
export interface RunMaintenanceResponseRecoverAdministrator {
    /** Root access revision after recovery. */
    access_revision_no: LoonFS.AccessRevisionNo;
    /** Recovery commit id. */
    commit_id: LoonFS.CommitId;
    /** Sequence assigned to the recovery commit. */
    committed_seq: LoonFS.ChangeSeq;
    /** Namespace whose root grants changed. */
    namespace_id: LoonFS.NamespaceId;
}
