// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Result of one metadata compaction unit.
 */
export interface RunMaintenanceResponseMetadataCompaction {
    /** The compaction outcome. */
    compaction: LoonFS.MetadataCompactionOutcome;
    /** Namespace compacted by this run. */
    namespace_id: LoonFS.NamespaceId;
}
