// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * One maintenance job for one namespace.
 */
export type RunMaintenanceRequest =
    | LoonFS.RunMaintenanceRequest.Gc
    | LoonFS.RunMaintenanceRequest.GrepGc
    | LoonFS.RunMaintenanceRequest.Metadata
    | LoonFS.RunMaintenanceRequest.MetadataCompaction
    | LoonFS.RunMaintenanceRequest.RecoverAdministrator
    | LoonFS.RunMaintenanceRequest.Retention;

export namespace RunMaintenanceRequest {
    export interface Gc extends LoonFS.RunMaintenanceRequestGc {
        kind: "gc";
    }

    export interface GrepGc extends LoonFS.RunMaintenanceRequestGrepGc {
        kind: "grep_gc";
    }

    export interface Metadata extends LoonFS.RunMaintenanceRequestMetadata {
        kind: "metadata";
    }

    export interface MetadataCompaction extends LoonFS.RunMaintenanceRequestMetadataCompaction {
        kind: "metadata_compaction";
    }

    export interface RecoverAdministrator extends LoonFS.RunMaintenanceRequestRecoverAdministrator {
        kind: "recover_administrator";
    }

    export interface Retention extends LoonFS.RunMaintenanceRequestRetention {
        kind: "retention";
    }
}
