// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * The result of one maintenance job. The `kind` matches the request.
 */
export type RunMaintenanceResponse =
    | LoonFS.RunMaintenanceResponse.Gc
    | LoonFS.RunMaintenanceResponse.Metadata
    | LoonFS.RunMaintenanceResponse.MetadataCompaction
    | LoonFS.RunMaintenanceResponse.RecoverAdministrator
    | LoonFS.RunMaintenanceResponse.Retention;

export namespace RunMaintenanceResponse {
    export interface Gc extends LoonFS.RunMaintenanceResponseGc {
        kind: "gc";
    }

    export interface Metadata extends LoonFS.RunMaintenanceResponseMetadata {
        kind: "metadata";
    }

    export interface MetadataCompaction extends LoonFS.RunMaintenanceResponseMetadataCompaction {
        kind: "metadata_compaction";
    }

    export interface RecoverAdministrator extends LoonFS.RunMaintenanceResponseRecoverAdministrator {
        kind: "recover_administrator";
    }

    export interface Retention extends LoonFS.RunMaintenanceResponseRetention {
        kind: "retention";
    }
}
