// This file was auto-generated by Fern from our API Definition.

/**
 * Folds the WAL tail and runs one bounded compaction step.
 */
export interface RunMaintenanceRequestMetadata {
    /**
     * The WAL tail length, in WAL objects, that triggers a fold. Omit it for
     * the server default.
     */
    max_wal_tail_objects?: number | undefined;
}
