// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Restores a root administrator.
 */
export interface RunMaintenanceRequestRecoverAdministrator {
    /** Principal receiving administrator rights. */
    principal_id: LoonFS.PrincipalId;
}
