// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Result of one bounded mark-and-sweep garbage-collection pass.
 */
export interface RunMaintenanceResponseGc {
    /** Whether the pass reached `max_steps` before completion. */
    budget_exhausted: boolean;
    /** Whether reference marking is unfinished, so content reclamation has not started. */
    content_reclamation_deferred: boolean;
    /** Objects the pass deleted, split by object family. */
    deleted: LoonFS.DeletedObjectCounts;
    /** Namespace the pass ran against. */
    namespace_id: LoonFS.NamespaceId;
    /** The opaque run token for remaining marking, sweeping, or cleanup work. */
    next_cursor?: string | undefined;
    /** The earliest known future reclamation time observed by this pass. */
    next_reclamation_at_ms?: number | undefined;
    /** The deleted head's irrevocable owner-prefix collection deadline. */
    reclaim_after_ms?: number | undefined;
    /** The checkpoint records released by the pass, grouped by reason. */
    released_checkpoints: LoonFS.ReleasedCheckpointCounts;
    /** `retained_candidates` grouped by reason. */
    retained: LoonFS.RetainedCandidates;
    /** The number of candidates retained at deletion time. */
    retained_candidates: number;
    /** True when ambiguous roots suppressed manifest/segment deletion. */
    retention_degraded: boolean;
}
