// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Response carrying one capability per requested part.
 */
export interface SignUploadPartsResponse {
    /** Namespace that owns the upload session. */
    namespace_id: LoonFS.NamespaceId;
    /** Capabilities in the order the request asked for them. */
    parts: LoonFS.SignedUploadPart[];
    /** Session the parts belong to. */
    upload_id: LoonFS.UploadId;
}
