// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * A live snapshot.
 */
export interface SnapshotSummary {
    /** Time the snapshot record was created, in Unix milliseconds. */
    created_at_ms: number;
    /** When the snapshot lease expires, in Unix milliseconds. */
    expires_at_ms: number;
    /** Namespace sequence captured by the snapshot. */
    head_seq: LoonFS.ChangeSeq;
    /** Snapshot label. */
    name: string;
    /** Namespace whose state the snapshot captured. */
    namespace_id: LoonFS.NamespaceId;
    /** Snapshot id. */
    snapshot_id: LoonFS.CheckpointId;
}
