// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * What one store contract probe observed, check by check.
 */
export interface StoreProbeResponse {
    /**
     * Every check the run performed, in the order it performed them. A
     * failed check lives here rather than in an error: the probe answered
     * the question, and the answer is that the store is wrong.
     */
    checks: LoonFS.StoreProbeCheckResult[];
    /**
     * Label the server minted for this run. It scopes the objects the run
     * wrote, so it identifies the run in provider logs too.
     */
    run_id: string;
}
