// This file was auto-generated by Fern from our API Definition.

/** What one contract check concluded about the store. */
export const StoreProbeCheckOutcome = {
    Passed: "passed",
    Unsupported: "unsupported",
    Failed: "failed",
} as const;
export type StoreProbeCheckOutcome = (typeof StoreProbeCheckOutcome)[keyof typeof StoreProbeCheckOutcome];
