// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * The ordered results from one store contract probe.
 */
export interface StoreProbeResponse {
    /** The check results in execution order. */
    checks: LoonFS.StoreProbeCheckResult[];
    /** The server-generated label for this probe run and its objects. */
    run_id: string;
}
