// This file was auto-generated by Fern from our API Definition.

/**
 * Options for one store contract probe. Empty today; a body is still sent
 * so later options do not change the shape of the request. An option this
 * build does not know is rejected rather than ignored, so a caller never
 * believes it selected something.
 */
export type StoreProbeRequest = Record<string, unknown>;
