// This file was auto-generated by Fern from our API Definition.

/**
 * Final: the session selected no content and its object is gone.
 */
export interface UploadSessionStatusAborted {
    /** Unix-millisecond stamp of the abort. */
    aborted_at_ms: number;
}
