// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * A request to complete an upload session using the mode that started it.
 */
export type UploadCompletion =
    | LoonFS.UploadCompletion.DirectMultipart
    | LoonFS.UploadCompletion.DirectPut
    | LoonFS.UploadCompletion.ServiceProxied;

export namespace UploadCompletion {
    export interface DirectMultipart extends LoonFS.CompleteUploadDirectMultipart {
        mode: "direct_multipart";
    }

    export interface DirectPut extends LoonFS.CompleteUploadDirectPut {
        mode: "direct_put";
    }

    export interface ServiceProxied extends LoonFS.CompleteUploadServiceProxied {
        mode: "service_proxied";
    }
}
