// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Final: the session selected no content and its object is gone.
 */
export interface UploadSessionStatusAborted {
    /** Unix-millisecond stamp of the abort. */
    aborted_at_ms: number;
    /** Transport selected when the session began. */
    mode: LoonFS.UploadMode;
    /** Namespace that owns the session. */
    namespace_id: LoonFS.NamespaceId;
    /** Session represented by this view. */
    upload_id: LoonFS.UploadId;
}
