// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Accepting content until its lease passes.
 */
export interface UploadSessionStatusOpen {
    /**
     * Unix-millisecond instant after which the session is abandoned and
     * may be aborted by server-side cleanup.
     */
    expires_at_ms: number;
    /** Transport selected when the session began. */
    mode: LoonFS.UploadMode;
    /** Namespace that owns the session. */
    namespace_id: LoonFS.NamespaceId;
    /** Session represented by this view. */
    upload_id: LoonFS.UploadId;
}
