// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Accepting content until its lease passes.
 */
export interface UploadSessionStatusOpen {
    /** The Unix-millisecond time after which cleanup may abort the session. */
    expires_at_ms: number;
    /** Transport selected when the session began. */
    mode: LoonFS.UploadMode;
    /** Namespace that owns the session. */
    namespace_id: LoonFS.NamespaceId;
    /** Session represented by this view. */
    upload_id: LoonFS.UploadId;
}
