// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * One part's checksum, supplied by the client so the server can sign it
 * into that part's upload URL.
 */
export interface UploadPartChecksumClaim {
    /** Checksum over this part's bytes. */
    checksum: LoonFS.Checksum;
    /** One-based part number, at most the provider's 10,000-part limit. */
    part_number: number;
}
