// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Current view of one upload session.
 */
export type UploadSession = LoonFS.UploadSession.Aborted | LoonFS.UploadSession.Completed | LoonFS.UploadSession.Open;

export namespace UploadSession {
    export interface Aborted extends LoonFS.UploadSessionStatusAborted {
        status: "aborted";
    }

    export interface Completed extends LoonFS.UploadSessionStatusCompleted {
        status: "completed";
    }

    export interface Open extends LoonFS.UploadSessionStatusOpen {
        status: "open";
    }
}
