// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Observed state of an upload session.
 *
 * A session starts as `Open` and ends as either `Completed` or `Aborted`.
 * Both final states are permanent. Reading a completed session issues a new
 * receipt for the durable content, so a lost commit response does not require
 * the content to be uploaded again.
 */
export type UploadSessionStatus =
    | LoonFS.UploadSessionStatus.Open
    | LoonFS.UploadSessionStatus.Completed
    | LoonFS.UploadSessionStatus.Aborted;

export namespace UploadSessionStatus {
    export interface Open extends LoonFS.UploadSessionStatusOpen {
        status: "open";
    }

    export interface Completed extends LoonFS.UploadSessionStatusCompleted {
        status: "completed";
    }

    export interface Aborted extends LoonFS.UploadSessionStatusAborted {
        status: "aborted";
    }
}
