// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Request to complete an upload session.
 *
 * `mode` must match the mode used to start the session. Direct uploads
 * include the expected content details. Multipart also includes its parts.
 */
export type UploadCompletion =
    | LoonFS.UploadCompletion.ServiceProxied
    | LoonFS.UploadCompletion.DirectPut
    | LoonFS.UploadCompletion.DirectMultipart;

export namespace UploadCompletion {
    export interface ServiceProxied extends LoonFS.CompleteUploadServiceProxied {
        mode: "service_proxied";
    }

    export interface DirectPut extends LoonFS.CompleteUploadDirectPut {
        mode: "direct_put";
    }

    export interface DirectMultipart extends LoonFS.CompleteUploadDirectMultipart {
        mode: "direct_multipart";
    }
}
