// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Size and checksum reported by the client for a complete payload.
 *
 * Direct uploads provide this at completion. The server verifies it against
 * the object stored by the provider.
 */
export interface UploadContentClaim {
    /** Whole-payload checksum in the algorithm required by this operation. */
    checksum: LoonFS.Checksum;
    /** Complete payload size in bytes. */
    size_bytes: number;
}
