// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Concurrent updates prevented every publication attempt.
 */
export interface WalFlushStepOutcomeRetriesExhausted {
    /** Head sequence observed before the step ran. */
    observed_head_seq: LoonFS.ChangeSeq;
}
