// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * A concurrent head update won the race.
 */
export interface WalFlushStepOutcomeRaceLost {
    /** Head sequence observed before the advance attempt. */
    observed_head_seq: LoonFS.ChangeSeq;
}
