// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * The step did not update the root because it already referenced a
 * different manifest.
 */
export interface WalFlushStepOutcomeAlreadyPublished {
    /** Sequence this step attempted to flush through. */
    attempted_seq: LoonFS.ChangeSeq;
    /** Manifest the root currently references. */
    current_manifest_no: LoonFS.ManifestNo;
}
