// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Concurrent updates prevented every attempt from publishing. Nothing
 * was flushed, and a later step can try again.
 */
export interface WalFlushStepOutcomeRetriesExhausted {
    /** Head sequence observed before the step ran. */
    observed_head_seq: LoonFS.ChangeSeq;
}
