// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * What the WAL fold part of a maintenance pass did.
 */
export type WalFoldStepOutcome =
    | LoonFS.WalFoldStepOutcome.AlreadyPublished
    | LoonFS.WalFoldStepOutcome.Folded
    | LoonFS.WalFoldStepOutcome.NotNeeded
    | LoonFS.WalFoldStepOutcome.RetriesExhausted;

export namespace WalFoldStepOutcome {
    export interface AlreadyPublished extends LoonFS.WalFoldStepOutcomeAlreadyPublished {
        outcome: "already_published";
    }

    export interface Folded extends LoonFS.WalFoldStepOutcomeFolded {
        outcome: "folded";
    }

    export interface NotNeeded extends LoonFS.WalFoldStepOutcomeNotNeeded {
        outcome: "not_needed";
    }

    export interface RetriesExhausted extends LoonFS.WalFoldStepOutcomeRetriesExhausted {
        outcome: "retries_exhausted";
    }
}
