// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * What the WAL-flush part of a maintenance pass did.
 */
export type WalFlushStepOutcome =
    | LoonFS.WalFlushStepOutcome.AlreadyPublished
    | LoonFS.WalFlushStepOutcome.Flushed
    | LoonFS.WalFlushStepOutcome.NotNeeded
    | LoonFS.WalFlushStepOutcome.RetriesExhausted;

export namespace WalFlushStepOutcome {
    export interface AlreadyPublished extends LoonFS.WalFlushStepOutcomeAlreadyPublished {
        outcome: "already_published";
    }

    export interface Flushed extends LoonFS.WalFlushStepOutcomeFlushed {
        outcome: "flushed";
    }

    export interface NotNeeded extends LoonFS.WalFlushStepOutcomeNotNeeded {
        outcome: "not_needed";
    }

    export interface RetriesExhausted extends LoonFS.WalFlushStepOutcomeRetriesExhausted {
        outcome: "retries_exhausted";
    }
}
