// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * The current manifest already covered the captured WAL tail; this step published no manifest.
 */
export interface WalFlushStepOutcomeAlreadyPublished {
    /** Sequence this step attempted to flush through. */
    attempted_seq: LoonFS.ChangeSeq;
    /** The namespace's current manifest number. */
    current_manifest_no: LoonFS.ManifestNo;
}
