// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * The step flushed the WAL tail and advanced the metadata root.
 */
export interface WalFlushStepOutcomeFlushed {
    /** Sequence covered by the published manifest. */
    manifest_head_seq: LoonFS.ChangeSeq;
}
