// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../index.js";

/**
 * @example
 *     {
 *         namespace_id: "namespace_id",
 *         pattern: "pattern"
 *     }
 */
export interface GrepRequest {
    /** Namespace id */
    namespace_id: string;
    /**
     * Permit a capped exhaustive scan when the pattern yields no required
     * grams. Refused beyond the server's scan budget.
     */
    allow_scan?: boolean;
    /**
     * When the unindexed tail exceeds the scan budget, return
     * indexed-only results (reported via `tail_scanned: false`) instead
     * of failing with `index_lagging`.
     */
    allow_stale?: boolean;
    /**
     * Match case-insensitively. Verification is exact; the index remains
     * consulted through its case-folded grams.
     */
    case_insensitive?: boolean;
    /**
     * Resume cursor from a previous page. The cursor resumes strictly
     * after the last candidate the issuing page finished scanning and is
     * bound to that page's request; each page is evaluated against the
     * namespace head at page time.
     */
    cursor?: string | null;
    /** Maximum matches per page. */
    limit?: number | null;
    /**
     * Restrict matches to files under this complete absolute path, resolved
     * to a directory inode before candidates are filtered.
     */
    path_prefix?: LoonFS.AbsolutePath;
    /**
     * The pattern, in the Rust `regex` crate's dialect (no backreferences
     * or lookaround). Patterns that require no literal bytes are rejected
     * with `query_unindexable` unless `allow_scan` is set.
     */
    pattern: string;
}
