// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as LoonFS from "../../../index.js";

export declare namespace SystemClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Server health, readiness, and metrics
 */
export class SystemClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SystemClient.Options>;

    constructor(options: SystemClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Returns `ok` when the server is running and can accept requests.
     *
     * @param {SystemClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link LoonFS.RequestTimeoutError}
     * @throws {@link errors.LoonFSError}
     * @throws {@link errors.LoonFSTimeoutError}
     *
     * @example
     *     await client.system.health()
     */
    public health(requestOptions?: SystemClient.RequestOptions): core.HttpResponsePromise<string> {
        return core.HttpResponsePromise.fromPromise(this.__health(requestOptions));
    }

    private async __health(requestOptions?: SystemClient.RequestOptions): Promise<core.WithRawResponse<string>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "health",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            responseType: "text",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as string, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 408:
                    throw new LoonFS.RequestTimeoutError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.LoonFSError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/health");
    }

    /**
     * Returns this process's metrics in Prometheus text exposition format 0.0.4. Unlike `/health` and `/readiness`, the route requires the deployment's bearer token.
     *
     * @param {SystemClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link LoonFS.UnauthorizedError}
     * @throws {@link LoonFS.RequestTimeoutError}
     * @throws {@link errors.LoonFSError}
     * @throws {@link errors.LoonFSTimeoutError}
     *
     * @example
     *     await client.system.getMetrics()
     */
    public getMetrics(requestOptions?: SystemClient.RequestOptions): core.HttpResponsePromise<string> {
        return core.HttpResponsePromise.fromPromise(this.__getMetrics(requestOptions));
    }

    private async __getMetrics(requestOptions?: SystemClient.RequestOptions): Promise<core.WithRawResponse<string>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "metrics",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            responseType: "text",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as string, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new LoonFS.UnauthorizedError(_response.error.body as LoonFS.ApiError, _response.rawResponse);
                case 408:
                    throw new LoonFS.RequestTimeoutError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.LoonFSError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/metrics");
    }

    /**
     * Returns `ready` while the server admits new work. Once shutdown begins and publisher admission closes, answers 503 `shutting_down` so load balancers can drain the instance. `/health` stays the liveness probe: it only reports that the process is up.
     *
     * @param {SystemClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link LoonFS.RequestTimeoutError}
     * @throws {@link LoonFS.ServiceUnavailableError}
     * @throws {@link errors.LoonFSError}
     * @throws {@link errors.LoonFSTimeoutError}
     *
     * @example
     *     await client.system.readiness()
     */
    public readiness(requestOptions?: SystemClient.RequestOptions): core.HttpResponsePromise<string> {
        return core.HttpResponsePromise.fromPromise(this.__readiness(requestOptions));
    }

    private async __readiness(requestOptions?: SystemClient.RequestOptions): Promise<core.WithRawResponse<string>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "readiness",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            responseType: "text",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as string, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 408:
                    throw new LoonFS.RequestTimeoutError(_response.error.body as unknown, _response.rawResponse);
                case 503:
                    throw new LoonFS.ServiceUnavailableError(
                        _response.error.body as LoonFS.ApiError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.LoonFSError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/readiness");
    }
}
