// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../index.js";

/**
 * @example
 *     {
 *         namespace_id: "namespace_id",
 *         upload_id: "upload_id",
 *         body: {
 *             mode: "service_proxied"
 *         }
 *     }
 */
export interface CompleteUploadRequest {
    /** Namespace id */
    namespace_id: string;
    /** Upload session id */
    upload_id: string;
    body: LoonFS.UploadCompletion;
}
