// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../index.js";

/**
 * @example
 *     {
 *         namespace_id: "namespace_id",
 *         upload_id: "upload_id",
 *         body: {
 *             mode: "direct_multipart",
 *             content: {
 *                 checksum: {
 *                     algorithm: "sha256",
 *                     value: "value"
 *                 },
 *                 size_bytes: 1000000
 *             },
 *             parts: [{
 *                     checksum: {
 *                         algorithm: "sha256",
 *                         value: "value"
 *                     },
 *                     etag: "etag",
 *                     part_number: 1
 *                 }]
 *         }
 *     }
 */
export interface CompleteUploadRequest {
    /** Namespace id */
    namespace_id: string;
    /** Upload session id */
    upload_id: string;
    body: LoonFS.UploadCompletion;
}
