// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         namespace_id: "namespace_id",
 *         upload_id: "upload_id"
 *     }
 */
export interface GetUploadStatusRequest {
    /** Namespace id */
    namespace_id: string;
    /** Upload session id */
    upload_id: string;
}
