// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../index.js";

/**
 * @example
 *     {
 *         namespace_id: "namespace_id",
 *         upload_id: "upload_id",
 *         parts: [{
 *                 checksum: {
 *                     algorithm: "sha256",
 *                     value: "value"
 *                 },
 *                 part_number: 1
 *             }]
 *     }
 */
export interface SignUploadPartsRequest {
    /** Namespace id */
    namespace_id: string;
    /** Upload session id */
    upload_id: string;
    /**
     * Parts to authorize and the checksum for each part. Requesting a part
     * again replaces the previous upload for that part number.
     */
    parts: LoonFS.UploadPartChecksumClaim[];
}
