// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         namespace_id: "namespace_id",
 *         name: "name"
 *     }
 */
export interface CreateCheckpointRequest {
    /** Namespace id */
    namespace_id: string;
    /**
     * Label recorded on the checkpoint record. A label, not a key: several
     * records may carry the same name over different bases.
     */
    name: string;
    /**
     * Optional lifetime; the server computes the record's expiry from its
     * own clock. Absent means the pin holds until explicitly released.
     */
    ttl_ms?: number | null;
}
