// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         namespace_id: "namespace_id"
 *     }
 */
export interface DisableGrepIndexRequest {
    /** Namespace id */
    namespace_id: string;
}
