// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         namespace_id: "namespace_id"
 *     }
 */
export interface GrepGcRequest {
    /** Namespace id */
    namespace_id: string;
    /**
     * Opaque resume token returned as `next_cursor` by an earlier pass
     * against the same namespace.
     */
    cursor?: string | null;
    /**
     * Reads this pass may spend before returning with a `next_cursor`.
     * Omit to take the same per-pass default the runtime's own collection
     * takes.
     */
    max_objects?: number | null;
}
