// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../index.js";

/**
 * @example
 *     {
 *         namespace_id: "namespace_id"
 *     }
 */
export interface MaintenanceStepRequest {
    /** Namespace id */
    namespace_id: string;
    /**
     * Run one bounded mark-and-sweep garbage-collection pass. Omit this
     * field to skip garbage collection.
     */
    gc?: LoonFS.GcRequest;
    /**
     * Flush the visible WAL tail into metadata segments, then run one bounded
     * reorganization step.
     */
    metadata_maintenance?: LoonFS.MetadataMaintenanceRequest;
    /**
     * Advance the retention floor to the flushed manifest head. Include this
     * field to select the action.
     */
    retention?: LoonFS.AdvanceRetentionRequest;
}
