// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../index.js";

/**
 * @example
 *     {
 *         namespace_id: "namespace_id"
 *     }
 */
export interface MaintenanceStepRequest {
    /** Namespace id */
    namespace_id: string;
    /**
     * Advance the retention floor to the flushed manifest head. Nothing
     * surrenders replay history unless this is true.
     */
    advance_retention?: boolean;
    /**
     * Run one bounded mark-and-sweep garbage-collection pass. Nothing
     * sweeps unless this is present.
     */
    gc?: LoonFS.GcRequest;
    /**
     * Flush the visible WAL tail into metadata tables, then run one bounded
     * reorganization step.
     */
    metadata?: LoonFS.MetadataMaintenanceRequest;
}
