// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         namespace_id: "namespace_id",
 *         checkpoint_id: "checkpoint_id"
 *     }
 */
export interface ReleaseCheckpointRequest {
    /** Namespace id */
    namespace_id: string;
    /** Checkpoint id */
    checkpoint_id: string;
}
