// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../index.js";

/**
 * @example
 *     {
 *         namespace_alias: "namespace_alias",
 *         path: "/docs/report.txt"
 *     }
 */
export interface BeginDownloadRequest {
    /** Application namespace alias */
    namespace_alias: string;
    /** Absolute path of the file to read. */
    path: LoonFS.AbsolutePath;
    /** Revision to read, or `None` for the path's current revision. */
    revision_no?: LoonFS.RevisionNo;
}
