// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../index.js";

/**
 * @example
 *     {
 *         mount: "mount",
 *         path: "path"
 *     }
 */
export interface GetFileBytesRequest {
    /** Application mount name */
    mount: string;
    /** Absolute file path */
    path: string;
    /** Optional prior revision number */
    revision_no?: LoonFS.RevisionNo;
}
