// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../index.js";

/**
 * @example
 *     {
 *         namespace_alias: "namespace_alias",
 *         path: "path",
 *         snapshot_id: "chk_00000000000000000000000000000002"
 *     }
 */
export interface GetPathEntryRequest {
    /** Application namespace alias */
    namespace_alias: string;
    /** Absolute filesystem path */
    path: string;
    /** Project the inode's attribute map and revision (`true` or `false`). Defaults to `true`: a stat answers for one path and a map is capped at 64 KiB. */
    include_attributes?: boolean;
    /** Use the path state captured by this snapshot */
    snapshot_id?: LoonFS.CheckpointId;
}
