// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         mount: "mount",
 *         path: "path"
 *     }
 */
export interface ListPathEntriesRequest {
    /** Application mount name */
    mount: string;
    /** Absolute filesystem path */
    path: string;
    /** Maximum page size */
    limit?: number;
    /** Opaque directory-list page cursor */
    cursor?: string;
    /** Project each entry's attribute map and revision (`true` or `false`). Defaults to `false`: a page holds many entries and each map may be 64 KiB, so a listing does not carry them unless asked. */
    include_attributes?: boolean;
}
