// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../index.js";

/**
 * @example
 *     {
 *         mount: "mount",
 *         after_seq: 1000000
 *     }
 */
export interface ListChangesRequest {
    /** Application mount name */
    mount: string;
    /** Return committed changes after this sequence */
    after_seq: LoonFS.ChangeSeq;
    /** Maximum page size */
    limit?: number;
}
