// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         mount: "mount",
 *         path: "path"
 *     }
 */
export interface ListFileRevisionsRequest {
    /** Application mount name */
    mount: string;
    /** Absolute file path */
    path: string;
    /** Maximum page size */
    limit?: number;
    /** Opaque file-revisions page cursor */
    cursor?: string;
}
