// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         mount: "mount"
 *     }
 */
export interface ListTrashRequest {
    /** Application mount name */
    mount: string;
    /** Maximum page size */
    limit?: number;
    /** Opaque trash page cursor */
    cursor?: string;
}
