// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         namespace_alias: "namespace_alias",
 *         path: "path"
 *     }
 */
export interface StatPathRequest {
    /** Application namespace alias */
    namespace_alias: string;
    /** Absolute filesystem path */
    path: string;
    /** Project the inode's attribute map and revision (`true` or `false`). Defaults to `true`: a stat answers for one path and a map is capped at 64 KiB. */
    include_attributes?: boolean;
}
