// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../index.js";

/**
 * @example
 *     {
 *         namespace_id: "namespace_id",
 *         inode_id: "ino_123",
 *         snapshot_id: "pin_00000000000000000001-0000000000000002"
 *     }
 */
export interface CreateDownloadByInodeRequest {
    /** Namespace id */
    namespace_id: string;
    /** File inode ID */
    inode_id: string;
    /** Use the file revision captured by this snapshot */
    snapshot_id?: LoonFS.PinId;
    /** First byte the capability reads. Defaults to 0 and must be below the file's size, except 0 for a file of zero bytes */
    start_offset?: number;
}
