// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../index.js";

/**
 * @example
 *     {
 *         namespace_id: "namespace_id",
 *         inode_id: "inode_id",
 *         revision_no: 1000000
 *     }
 */
export interface GetFileRevisionBytesByInodeRequest {
    /** Namespace id */
    namespace_id: string;
    /** File inode ID */
    inode_id: string;
    /** Revision number */
    revision_no: LoonFS.RevisionNo;
}
