// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../index.js";

/**
 * @example
 *     {
 *         namespace_id: "namespace_id",
 *         inode_id: "inode_id"
 *     }
 */
export interface GetFileBytesByInodeRequest {
    /** Namespace id */
    namespace_id: string;
    /** File inode ID */
    inode_id: string;
    /** Use the file revision captured by this snapshot */
    snapshot_id?: LoonFS.PinId;
}
