// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         namespace_id: "namespace_id",
 *         inode_id: "ino_123"
 *     }
 */
export interface ListInodeChildrenRequest {
    /** Namespace id */
    namespace_id: string;
    /** Directory inode ID */
    inode_id: string;
    /** Maximum page size */
    limit?: number;
    /** Opaque directory page cursor */
    cursor?: string;
    /** Project each entry's attribute map and revision (`true` or `false`). Defaults to `false`: a page holds many entries and each map may be 64 KiB, so a listing does not carry them unless asked. */
    include_attributes?: boolean;
}
