// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         namespace_id: "namespace_id",
 *         inode_id: "ino_123"
 *     }
 */
export interface ListFileRevisionsByInodeRequest {
    /** Namespace id */
    namespace_id: string;
    /** File inode ID */
    inode_id: string;
    /** Maximum page size */
    limit?: number;
    /** Opaque file-revisions page cursor */
    cursor?: string;
}
