// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../index.js";

/**
 * @example
 *     {
 *         namespace_id: "namespace_id",
 *         inode_id: "ino_123",
 *         snapshot_id: "pin_00000000000000000001-0000000000000002"
 *     }
 */
export interface ListInodeChildrenRequest {
    /** Namespace id */
    namespace_id: string;
    /** Directory inode ID */
    inode_id: string;
    /** Maximum page size */
    limit?: number;
    /** Opaque directory page cursor */
    cursor?: string;
    /** Project each entry's attribute map and revision (`true` or `false`). Defaults to `false`: a page holds many entries and each map may be 64 KiB, so a listing does not carry them unless asked. */
    include_attributes?: boolean;
    /** Use the directory state captured by this snapshot */
    snapshot_id?: LoonFS.PinId;
}
