// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         namespace_id: "namespace_id",
 *         inode_id: "ino_123"
 *     }
 */
export interface StatInodeRequest {
    /** Namespace id */
    namespace_id: string;
    /** Inode ID */
    inode_id: string;
    /** Project the inode's attribute map and revision (`true` or `false`). Defaults to `true`: a stat answers for one path and a map is capped at 64 KiB. */
    include_attributes?: boolean;
}
