// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { CheckpointsClient } from "../resources/checkpoints/client/Client.js";
import { DiagnosticsClient } from "../resources/diagnostics/client/Client.js";
import { GrepIndexClient } from "../resources/grepIndex/client/Client.js";
import { MaintenanceClient } from "../resources/maintenance/client/Client.js";
import { StoreClient } from "../resources/store/client/Client.js";

export declare namespace AdminClient {
    export type Options = BaseClientOptions;
}

export class AdminClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<AdminClient.Options>;
    protected _checkpoints: CheckpointsClient | undefined;
    protected _diagnostics: DiagnosticsClient | undefined;
    protected _grepIndex: GrepIndexClient | undefined;
    protected _maintenance: MaintenanceClient | undefined;
    protected _store: StoreClient | undefined;

    constructor(options: AdminClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get checkpoints(): CheckpointsClient {
        return (this._checkpoints ??= new CheckpointsClient(this._options));
    }

    public get diagnostics(): DiagnosticsClient {
        return (this._diagnostics ??= new DiagnosticsClient(this._options));
    }

    public get grepIndex(): GrepIndexClient {
        return (this._grepIndex ??= new GrepIndexClient(this._options));
    }

    public get maintenance(): MaintenanceClient {
        return (this._maintenance ??= new MaintenanceClient(this._options));
    }

    public get store(): StoreClient {
        return (this._store ??= new StoreClient(this._options));
    }
}
