// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         namespace_id: "namespace_id",
 *         snapshot_id: "snapshot_id",
 *         ttl_ms: 1000000
 *     }
 */
export interface ExtendSnapshotRequest {
    /** Namespace id */
    namespace_id: string;
    /** Snapshot id */
    snapshot_id: string;
    /** Requested lifetime from the server's current time, in milliseconds. */
    ttl_ms: number;
}
