// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         namespace_id: "namespace_id"
 *     }
 */
export interface ListSnapshotsRequest {
    /** Namespace id */
    namespace_id: string;
    /** Maximum page size */
    limit?: number;
    /** Opaque snapshot-list page cursor */
    cursor?: string;
}
