// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../index.js";

/**
 * @example
 *     {
 *         namespace_id: "namespace_id",
 *         path: "path",
 *         snapshot_id: "chk_00000000000000000000000000000002"
 *     }
 */
export interface ListPathEntriesRequest {
    /** Namespace id */
    namespace_id: string;
    /** Absolute filesystem path */
    path: string;
    /** Maximum page size */
    limit?: number;
    /** Opaque directory-list page cursor */
    cursor?: string;
    /** Project each entry's attribute map and revision (`true` or `false`). Defaults to `false`: a page holds many entries and each map may be 64 KiB, so a listing does not carry them unless asked. */
    include_attributes?: boolean;
    /** Use the directory state captured by this snapshot */
    snapshot_id?: LoonFS.CheckpointId;
}
