// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../index.js";

/**
 * @example
 *     {
 *         namespace_id: "namespace_id",
 *         after_seq: 1000000,
 *         snapshot_id: "chk_00000000000000000000000000000002"
 *     }
 */
export interface ListChangesRequest {
    /** Namespace id */
    namespace_id: string;
    /** Return committed changes after this sequence */
    after_seq: LoonFS.ChangeSeq;
    /** Maximum page size */
    limit?: number;
    /** End the feed at this snapshot's captured sequence */
    snapshot_id?: LoonFS.CheckpointId;
}
