// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../../../../../../index.js";

/**
 * @example
 *     {
 *         namespace_id: "namespace_id",
 *         body: {
 *             "key": "value"
 *         }
 *     }
 */
export interface GcGrepIndexRequest {
    /** Namespace id */
    namespace_id: string;
    body: LoonFS.GrepGcRequest;
}
