// This file was auto-generated by Fern from our API Definition.

/** The type of actor responsible for a commit. */
export const ActorKind = {
    User: "user",
    Service: "service",
    System: "system",
} as const;
export type ActorKind = (typeof ActorKind)[keyof typeof ActorKind];
