// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Attributes returned for one inode.
 *
 * A path entry omits this entire group unless the caller requests attributes.
 * OpenAPI flattens these fields with `allOf`, so none of them can be marked as
 * required on every path entry.
 */
export interface AttributesProjection {
    /**
     * The complete attribute map at `attributes_revision_no`.
     *
     * An inode that has never had attributes written is at revision 0 with
     * an empty map.
     */
    attributes?: LoonFS.Attributes | undefined;
    /** The attribute revision this projection represents. */
    attributes_revision_no?: LoonFS.AttributeRevisionNo | undefined;
    /**
     * Time of the latest attribute update, in Unix milliseconds. This is
     * `None` for the initial empty state at revision 0.
     */
    attributes_updated_at_ms?: (number | null) | undefined;
    /**
     * Actor responsible for the latest attribute update. This is `None` for
     * the initial empty state at revision 0.
     */
    attributes_updated_by?: LoonFS.ActorRef | undefined;
}
