// This file was auto-generated by Fern from our API Definition.

/**
 * One validated attribute value.
 *
 * A value is at most [`MAX_ATTRIBUTE_VALUE_BYTES`] UTF-8 bytes. It is
 * otherwise free text: control characters and the empty string are legal.
 * Empty is a stored value, not a tombstone; only an explicit remove
 * operation deletes an attribute.
 */
export type AttributeValue = string;
