// This file was auto-generated by Fern from our API Definition.

/**
 * A validated inode attribute name from 1 to 128 UTF-8 bytes without control characters.
 *
 * Names are byte-exact; writes reject the reserved `loonfs.` prefix even though
 * the type accepts it.
 */
export type AttributeKey = string;
