// This file was auto-generated by Fern from our API Definition.

/**
 * A validated inode attribute value of at most [`MAX_ATTRIBUTE_VALUE_BYTES`] UTF-8 bytes.
 *
 * Empty strings and control characters are valid, and only an explicit remove
 * operation deletes an attribute.
 */
export type AttributeValue = string;
