// This file was auto-generated by Fern from our API Definition.

/**
 * Validated name of one inode attribute.
 *
 * A key is 1 to 128 UTF-8 bytes and carries no Unicode control
 * character, which is also what rejects NUL. Keys are compared exactly:
 * nothing case-folds or normalizes them, so two spellings that differ in
 * any byte name two different attributes.
 *
 * The `loonfs.` prefix is reserved for system-owned attributes. This
 * type accepts a reserved key, because a durable row has to be able to
 * carry a system attribute. The write operation is where a caller's
 * attempt to write a reserved key is rejected.
 */
export type AttributeKey = string;
