// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * The service will receive the bytes and write the content object.
 */
export interface BeginUploadResponseServiceProxied {
    /** Namespace authorized to consume the eventual staged content. */
    namespace_id: LoonFS.NamespaceId;
    /**
     * Durable session identity used by subsequent append and completion
     * calls.
     */
    upload_id: LoonFS.UploadId;
}
