// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Write the object in parts through presigned part uploads.
 */
export interface BeginUploadDirectMultipart {
    /** Part size options. The server uses its default when omitted. */
    multipart?: LoonFS.DirectMultipartUploadOptions | undefined;
}
