// This file was auto-generated by Fern from our API Definition.

/**
 * Write the whole object through one presigned request.
 */
export interface BeginUploadDirectPut {
    /** Advisory byte length for an early provider-limit check. */
    size_bytes?: number | undefined;
}
