// This file was auto-generated by Fern from our API Definition.

/** A supported checksum algorithm. */
export const ChecksumAlgorithm = {
    Crc64Nvme: "crc64nvme",
    Crc32C: "crc32c",
} as const;
export type ChecksumAlgorithm = (typeof ChecksumAlgorithm)[keyof typeof ChecksumAlgorithm];
