// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * A checksum algorithm and its canonical lowercase hexadecimal value.
 */
export interface Checksum {
    /** Algorithm that produced `value`. */
    algorithm: LoonFS.ChecksumAlgorithm;
    /** The canonical lowercase hexadecimal checksum without a prefix. */
    value: string;
}
