// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Requires no visible entry at the full path.
 */
export interface CommitPreconditionPathAbsence {
    /** Absolute path to check, including the root. */
    path: LoonFS.AbsolutePath;
}
