// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Requires a visible inode with the attribute revision the caller read.
 */
export interface CommitPreconditionAttributesRevision {
    /** Attribute revision observed by the caller. */
    expected_attributes_revision_no: LoonFS.AttributesRevisionNo;
    /** Inode whose state the caller read. */
    inode_id: LoonFS.InodeId;
}
