// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Requires a visible inode with the content revision the caller read.
 */
export interface CommitAssertionFileRevision {
    /** Content revision observed by the caller. */
    expected_revision_no: LoonFS.RevisionNo;
    /** Inode whose state the caller read. */
    inode_id: LoonFS.InodeId;
}
