// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Requires the pre-state head sequence to equal `expected_head_seq`.
 */
export interface CommitAssertionNamespaceHead {
    /** Sequence observed when the caller read its inputs. */
    expected_head_seq: LoonFS.ChangeSeq;
}
