// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Result of one commit.
 *
 * Every commit resolves to this envelope — path-oriented operations and
 * explicit commits, embedded or remote. The commit id is the caller's
 * reconciliation handle: resubmitting the same request with the same id
 * replays this result instead of committing twice.
 */
export interface CommitResponse {
    /**
     * Idempotency key the commit landed under: caller-supplied, or
     * generated on the caller's behalf when the request carried none.
     */
    commit_id: LoonFS.CommitId;
    /** Sequence number where the commit became visible. */
    committed_seq: LoonFS.ChangeSeq;
    /** Namespace that changed. */
    namespace_id: LoonFS.NamespaceId;
}
