// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Admission conditions checked against the candidate's pre-state before its operations.
 * The pre-state head sequence is the last admitted commit's sequence in the batch,
 * or the batch's base head sequence when no earlier candidate was admitted.
 */
export type CommitPrecondition =
    | LoonFS.CommitPrecondition.AccessRevision
    | LoonFS.CommitPrecondition.AttributesRevision
    | LoonFS.CommitPrecondition.FileRevision
    | LoonFS.CommitPrecondition.NamespaceHead
    | LoonFS.CommitPrecondition.PathAbsence
    | LoonFS.CommitPrecondition.PathBinding;

export namespace CommitPrecondition {
    export interface AccessRevision extends LoonFS.CommitPreconditionAccessRevision {
        kind: "access_revision";
    }

    export interface AttributesRevision extends LoonFS.CommitPreconditionAttributesRevision {
        kind: "attributes_revision";
    }

    export interface FileRevision extends LoonFS.CommitPreconditionFileRevision {
        kind: "file_revision";
    }

    export interface NamespaceHead extends LoonFS.CommitPreconditionNamespaceHead {
        kind: "namespace_head";
    }

    export interface PathAbsence extends LoonFS.CommitPreconditionPathAbsence {
        kind: "path_absence";
    }

    export interface PathBinding extends LoonFS.CommitPreconditionPathBinding {
        kind: "path_binding";
    }
}
