// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Requires the path to retain the binding or absence the caller read.
 */
export interface CommitAssertionBinding {
    /** Requires an inode expectation and detects moves away and back. */
    expected_binding_generation?: LoonFS.BindingGeneration | undefined;
    /** When absent, requires the path to be unbound. */
    expected_inode_id?: LoonFS.InodeId | undefined;
    /** Absolute path to check, including the root. */
    path: LoonFS.AbsolutePath;
}
