// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Complete a direct-PUT upload.
 */
export interface CompleteUploadDirectPut {
    /** Expected length and checksum of the stored object. */
    content: LoonFS.UploadContentClaim;
}
