// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Proof that a specific `content_ref` may be used in a later commit.
 */
export interface ContentToken {
    /** Content authorized by this token. */
    content_ref: LoonFS.ContentRef;
    /** The opaque server-signed token that clients must not parse. */
    token: string;
}
