// This file was auto-generated by Fern from our API Definition.

/** A supported content reference kind serialized as a string. */
export const ContentRefKind = {
    BlobV1: "blob_v1",
} as const;
export type ContentRefKind = (typeof ContentRefKind)[keyof typeof ContentRefKind];
