// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Signed object ranges for one revision.
 */
export interface CreateDownloadResponse {
    /** The identity, byte length, and checksum of the revision's bytes. */
    content_ref: LoonFS.ContentRef;
    /** Namespace that was read. */
    namespace_id: LoonFS.NamespaceId;
    /** Absolute path as rendered from stored display names. */
    path: LoonFS.AbsolutePath;
    /** The revision's bytes from the requested offset, in order. */
    ranges: LoonFS.DownloadRange[];
    /** Revision the capability reads, resolved from the request. */
    revision_no: LoonFS.RevisionNo;
}
