// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Selects the transport for a new upload session.
 */
export type CreateUploadBody =
    | LoonFS.CreateUploadBody.DirectMultipart
    | LoonFS.CreateUploadBody.DirectPut
    | LoonFS.CreateUploadBody.ServiceProxied;

export namespace CreateUploadBody {
    export interface DirectMultipart extends LoonFS.CreateUploadBodyDirectMultipart {
        mode: "direct_multipart";
    }

    export interface DirectPut extends LoonFS.CreateUploadBodyDirectPut {
        mode: "direct_put";
    }

    export interface ServiceProxied extends LoonFS.CreateUploadBodyServiceProxied {
        mode: "service_proxied";
    }
}
