// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Identifies the snapshot record that was deleted.
 */
export interface DeleteSnapshotResponse {
    /** Namespace the snapshot belonged to. */
    namespace_id: LoonFS.NamespaceId;
    /** Deleted snapshot record. */
    snapshot_id: LoonFS.SnapshotId;
}
