// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * A directory entry's parent and name.
 */
export interface DirectoryBinding {
    /** Name shown to users. */
    display_name: LoonFS.DisplayName;
    /** Name used to look up the entry. */
    name_key: LoonFS.NameKey;
    /** Stable inode ID within a namespace */
    parent_inode_id: string;
}
