// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Details for a direct PUT upload.
 */
export interface DirectPutUpload {
    /** Short-lived permission to write the object. */
    access: LoonFS.ObjectTransferAccess;
    /** Checksum algorithm the client must use for its completion claim. */
    checksum_algorithm: LoonFS.ChecksumAlgorithm;
}
