// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Settings returned for a direct multipart upload.
 */
export interface DirectMultipartUpload {
    /** Checksum algorithm for every part and for the complete payload. */
    checksum_algorithm: LoonFS.ChecksumAlgorithm;
    /**
     * Byte length of every part except the last. At most 10,000 parts may
     * be uploaded, so this bounds the object at `part_size_bytes × 10_000`.
     */
    part_size_bytes: number;
}
