// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Optional machine-readable details for an [`ApiError`].
 *
 * Clients make retry decisions from the error code and use these fields for
 * relevant identifiers such as commit ids, writer epochs, and revisions.
 * Fields may be absent and clients must ignore fields they do not use.
 */
export interface ErrorDetails {
    /**
     * Unix milliseconds at which the current epoch's acquirer took it, when
     * the head recorded one. Writer ids are process labels, so two runs on
     * one machine can share one; the stamp is what tells them apart.
     */
    active_acquired_at_ms?: number | undefined;
    /**
     * Writer id recorded by the current epoch's acquirer, when the head
     * recorded one.
     */
    active_writer?: string | undefined;
    /** Epoch that currently owns the namespace. */
    active_writer_epoch?: LoonFS.WriterEpoch | undefined;
    /** Attribute revision that is actually current for the inode. */
    actual_attributes_revision_no?: LoonFS.AttributeRevisionNo | undefined;
    /** Deletion generation actually active for the inode. */
    actual_deletion_seq?: LoonFS.ChangeSeq | undefined;
    /**
     * Head sequence the namespace was actually at, which is what a caller
     * that still means to delete it retries against.
     */
    actual_head_seq?: LoonFS.ChangeSeq | undefined;
    /** Stable inode ID within a namespace */
    actual_inode_id?: string | undefined;
    /** Revision that is actually current; absent when the inode has none. */
    actual_revision_no?: LoonFS.RevisionNo | undefined;
    /** Change-feed cursor the request asked to resume after. */
    after_seq?: LoonFS.ChangeSeq | undefined;
    /** Idempotency key of the commit the error concerns. */
    commit_id?: LoonFS.CommitId | undefined;
    /**
     * Semantic identity of the mutation that already landed under that
     * commit id, from the same receipt as `committed_seq` and present
     * exactly when it is. A retry recomputes this value from the request it
     * just made — see
     * [`put_retry_fingerprint`](crate::put_retry_fingerprint) — and equality
     * is what proves the two are the same request.
     */
    committed_fingerprint?: string | undefined;
    /**
     * Sequence at which that commit id already landed. Present when the
     * failure was decided against a durable commit receipt, which is what
     * holds the sequence; absent when nothing has committed under the id
     * yet and two live requests are simply claiming it at once.
     */
    committed_seq?: LoonFS.ChangeSeq | undefined;
    /** Attribute revision the request expected to be current. */
    expected_attributes_revision_no?: LoonFS.AttributeRevisionNo | undefined;
    /** Deletion generation the undelete expected to be active. */
    expected_deletion_seq?: LoonFS.ChangeSeq | undefined;
    /**
     * Head sequence a namespace delete required the namespace to still be
     * at.
     */
    expected_head_seq?: LoonFS.ChangeSeq | undefined;
    /** Stable inode ID within a namespace */
    expected_inode_id?: string | undefined;
    /** Revision the request expected to be current. */
    expected_revision_no?: LoonFS.RevisionNo | undefined;
    /** Epoch the failing writer session held when it was displaced. */
    fenced_writer_epoch?: LoonFS.WriterEpoch | undefined;
    /** Stable inode ID within a namespace */
    inode_id?: string | undefined;
    /**
     * Position, in the request's operation list, of the operation that
     * failed. A commit applies all of its operations or none of them, so
     * this names the one that stopped the whole request.
     */
    operation_index?: number | undefined;
    /** Oldest sequence still promised for incremental replay. */
    retention_floor_seq?: LoonFS.ChangeSeq | undefined;
}
