// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * A file and its first revision were created.
 */
export interface FilesystemChangeFileCreated {
    /** Opaque identifier for the binding created by this event. */
    binding_generation: string;
    /** Content of the first revision. */
    content_ref: LoonFS.ContentRef;
    /** User-facing spelling of the new entry. */
    display_name: LoonFS.DisplayName;
    /** Stable inode ID within a namespace */
    inode_id: string;
    /** Stable inode ID within a namespace */
    parent_inode_id: string;
    /** First revision number. */
    revision_no: LoonFS.RevisionNo;
}
