// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * A file received a new current revision — a put over an existing
 * file, or a revision restore (one durable fact for both).
 */
export interface FilesystemChangeContentChanged {
    /** Immutable content published by the revision. */
    content_ref: LoonFS.ContentRef;
    /** Stable inode ID within a namespace */
    inode_id: string;
    /** New monotonic position in that file's revision history. */
    revision_no: LoonFS.RevisionNo;
}
