// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Write and remove attributes on a visible inode.
 */
export interface FilesystemOperationUpdateAttributesByInode {
    /** The attribute revision that must still be current. */
    expected_attributes_revision_no?: LoonFS.AttributesRevisionNo | undefined;
    /** Visible file or directory to update. */
    inode_id: LoonFS.InodeId;
    /** The attribute keys to remove, including duplicates that validation must reject. */
    remove?: LoonFS.AttributeKey[] | undefined;
    /**
     * The attributes to write, replacing values for matching keys and leaving
     * other keys unchanged.
     */
    set?: Record<string, LoonFS.AttributeValue> | undefined;
}
