// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * A deleted inode was recovered and re-bound.
 */
export interface FilesystemChangeUndeleted {
    /** Opaque identifier for the binding created by this event. */
    binding_generation: LoonFS.BindingGeneration;
    /** Spelling of the recovered binding. */
    display_name: LoonFS.DisplayName;
    /** Recovered inode. */
    inode_id: LoonFS.InodeId;
    /** Directory the recovered entry was bound under. */
    parent_inode_id: LoonFS.InodeId;
}
