// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Create a file under an existing parent inode. The name must be unused.
 */
export interface FilesystemOperationPutFileByInode {
    /** Immutable bytes that must be covered by a valid preparation proof. */
    content_ref: LoonFS.ContentRef;
    /** New file name. */
    display_name: LoonFS.DisplayName;
    /** Stable inode ID within a namespace */
    parent_inode_id: string;
}
