// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * A directory was created.
 */
export interface FilesystemChangeDirectoryCreated {
    /** Opaque identifier for the binding created by this event. */
    binding_version: LoonFS.BindingVersion;
    /** User-facing spelling of the new entry. */
    display_name: LoonFS.DisplayName;
    /** Newly allocated namespace-scoped inode identity. */
    inode_id: LoonFS.InodeId;
    /** Directory the new entry was bound under. */
    parent_inode_id: LoonFS.InodeId;
}
