// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * An inode's attributes changed.
 */
export interface FilesystemChangeAttributesChanged {
    /**
     * The inode's complete attribute map after the update, including an empty map
     * when all attributes were cleared.
     */
    attributes: LoonFS.Attributes;
    /** New attribute revision for that inode. */
    attributes_revision_no: LoonFS.AttributeRevisionNo;
    /** Inode whose attributes advanced. */
    inode_id: LoonFS.InodeId;
}
