// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * An inode moved to a new parent directory or name.
 */
export interface FilesystemChangeMoved {
    /** Opaque identifier for the binding created by this event. */
    binding_generation: string;
    /** Spelling of the old binding. */
    from_display_name: LoonFS.DisplayName;
    /** Stable inode ID within a namespace */
    from_parent_inode_id: string;
    /** Stable inode ID within a namespace */
    inode_id: string;
    /** Spelling of the new binding. */
    to_display_name: LoonFS.DisplayName;
    /** Stable inode ID within a namespace */
    to_parent_inode_id: string;
}
