// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * One filesystem operation.
 *
 * Unknown fields are rejected, and fieldless variants require empty objects.
 */
export type FilesystemOperation =
    | LoonFS.FilesystemOperation.CopyByInode
    | LoonFS.FilesystemOperation.CopyPath
    | LoonFS.FilesystemOperation.CreateDirectory
    | LoonFS.FilesystemOperation.CreateDirectoryByInode
    | LoonFS.FilesystemOperation.CreateFileByInode
    | LoonFS.FilesystemOperation.DeleteByInode
    | LoonFS.FilesystemOperation.DeletePath
    | LoonFS.FilesystemOperation.MoveByInode
    | LoonFS.FilesystemOperation.MovePath
    | LoonFS.FilesystemOperation.PutFile
    | LoonFS.FilesystemOperation.PutFileRevisionByInode
    | LoonFS.FilesystemOperation.RestoreRevision
    | LoonFS.FilesystemOperation.RestoreRevisionByInode
    | LoonFS.FilesystemOperation.Undelete
    | LoonFS.FilesystemOperation.UpdateAccess
    | LoonFS.FilesystemOperation.UpdateAccessByInode
    | LoonFS.FilesystemOperation.UpdateAttributes
    | LoonFS.FilesystemOperation.UpdateAttributesByInode;

export namespace FilesystemOperation {
    export interface CopyByInode extends LoonFS.FilesystemOperationCopyByInode {
        kind: "copy_by_inode";
    }

    export interface CopyPath extends LoonFS.FilesystemOperationCopyPath {
        kind: "copy_path";
    }

    export interface CreateDirectory extends LoonFS.FilesystemOperationCreateDirectory {
        kind: "create_directory";
    }

    export interface CreateDirectoryByInode extends LoonFS.FilesystemOperationCreateDirectoryByInode {
        kind: "create_directory_by_inode";
    }

    export interface CreateFileByInode extends LoonFS.FilesystemOperationCreateFileByInode {
        kind: "create_file_by_inode";
    }

    export interface DeleteByInode extends LoonFS.FilesystemOperationDeleteByInode {
        kind: "delete_by_inode";
    }

    export interface DeletePath extends LoonFS.FilesystemOperationDeletePath {
        kind: "delete_path";
    }

    export interface MoveByInode extends LoonFS.FilesystemOperationMoveByInode {
        kind: "move_by_inode";
    }

    export interface MovePath extends LoonFS.FilesystemOperationMovePath {
        kind: "move_path";
    }

    export interface PutFile extends LoonFS.FilesystemOperationPutFile {
        kind: "put_file";
    }

    export interface PutFileRevisionByInode extends LoonFS.FilesystemOperationPutFileRevisionByInode {
        kind: "put_file_revision_by_inode";
    }

    export interface RestoreRevision extends LoonFS.FilesystemOperationRestoreRevision {
        kind: "restore_revision";
    }

    export interface RestoreRevisionByInode extends LoonFS.FilesystemOperationRestoreRevisionByInode {
        kind: "restore_revision_by_inode";
    }

    export interface Undelete extends LoonFS.FilesystemOperationUndelete {
        kind: "undelete";
    }

    export interface UpdateAccess extends LoonFS.FilesystemOperationUpdateAccess {
        kind: "update_access";
    }

    export interface UpdateAccessByInode extends LoonFS.FilesystemOperationUpdateAccessByInode {
        kind: "update_access_by_inode";
    }

    export interface UpdateAttributes extends LoonFS.FilesystemOperationUpdateAttributes {
        kind: "update_attributes";
    }

    export interface UpdateAttributesByInode extends LoonFS.FilesystemOperationUpdateAttributesByInode {
        kind: "update_attributes_by_inode";
    }
}
