// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Create or replace one file with an already-durable content ref.
 */
export interface FilesystemOperationPutFile {
    /** Whether an existing file may receive a new revision instead of causing a conflict. */
    behavior?: LoonFS.DestinationBehavior | undefined;
    /** Immutable bytes that must be covered by a valid preparation proof. */
    content_ref: LoonFS.ContentRef;
    /**
     * When set (with `replace` behavior), the put applies only while
     * the file's current revision is still this one; a raced write
     * fails the request instead of silently stacking on it, and a
     * missing file answers `path_not_found`.
     */
    expected_revision_no?: LoonFS.RevisionNo | undefined;
    /** Absolute destination path; missing ancestors are created automatically. */
    path: LoonFS.AbsolutePath;
}
