// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Copy a file inode to a name under a parent inode.
 */
export interface FilesystemOperationCopyByInode {
    /** Whether an existing destination file may be replaced. */
    behavior?: LoonFS.DestinationBehavior | undefined;
    /** Name of the copy. */
    destination_display_name: LoonFS.DisplayName;
    /** Destination directory. */
    destination_parent_inode_id: LoonFS.InodeId;
    /** With `replace` behavior, the destination inode required by the request. */
    expected_destination_inode_id?: LoonFS.InodeId | undefined;
    /** With `replace` behavior and an inode precondition, the required content revision. */
    expected_destination_revision_no?: LoonFS.RevisionNo | undefined;
    /** File to copy. */
    inode_id: LoonFS.InodeId;
}
