// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Delete one path.
 */
export interface FsOpDeletePath {
    /** Whether a non-empty directory may be tombstoned recursively. */
    behavior?: LoonFS.DeleteDirectoryBehavior | undefined;
    /** Stable inode ID within a namespace */
    expected_inode_id?: string | undefined;
    /** Absolute path that must resolve to a visible inode. */
    path: LoonFS.AbsolutePath;
}
