// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Create one directory.
 */
export interface FsOpCreateDirectory {
    /**
     * Also create missing ancestor directories (the same auto-create
     * `put_file` performs). The final component must still be new.
     */
    parents?: boolean | undefined;
    /** Absolute destination path, rejected when invalid or already bound. */
    path: LoonFS.AbsolutePath;
}
