// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Restore an older revision as the current revision for a path.
 */
export interface FsOpRestoreRevision {
    /** Absolute path that must resolve to a visible file. */
    path: LoonFS.AbsolutePath;
    /** Existing historical revision whose content will be copied into a new current revision. */
    source_revision_no: LoonFS.RevisionNo;
}
