// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * One line-oriented match.
 */
export interface GrepMatch {
    /** Byte offset of the match within the file. */
    byte_offset: number;
    /** Stable inode ID within a namespace */
    inode_id: string;
    /** The matching line, truncated to the server's line cap. */
    line: string;
    /** One-based line number of the match. */
    line_number: number;
    /** True when `line` was truncated. */
    line_truncated: boolean;
    /** The file's absolute path, derived at the snapshot. */
    path: LoonFS.AbsolutePath;
    /** The matched revision (the newest visible one at the snapshot). */
    revision_no: LoonFS.RevisionNo;
}
