// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * One content-search page.
 */
export interface GrepResponse {
    /** Commits at or below this sequence were answered from the index. */
    built_through_seq: LoonFS.ChangeSeq;
    /**
     * Sequence this page was evaluated at. Pages are evaluated against
     * the namespace head at page time; the cursor is an ordering resume,
     * not a snapshot pin.
     */
    head_seq: LoonFS.ChangeSeq;
    /**
     * Matches in ascending `(inode_id, byte_offset)` order. A page may
     * return fewer matches than its limit and still carry a cursor: the
     * per-page verified-candidate budget bounds how much content one
     * request reads, whatever the plan's false-positive rate.
     */
    matches: LoonFS.GrepMatch[];
    /** Namespace searched. */
    namespace_id: LoonFS.NamespaceId;
    /** Present when another page follows. */
    next_cursor?: string | undefined;
    /**
     * True when revisions after `built_through_seq` were scanned
     * exhaustively; false only when `allow_stale` skipped them.
     */
    tail_scanned: boolean;
}
