// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Response for listing file revisions.
 */
export interface ListFileRevisionsResponse {
    /** Namespace head sequence used for the read. */
    head_seq: LoonFS.ChangeSeq;
    /** Stable inode ID within a namespace */
    inode_id: string;
    /** Namespace that was read. */
    namespace_id: LoonFS.NamespaceId;
    /** Opaque cursor for the next page, if more revisions are available. */
    next_cursor?: (string | null) | undefined;
    /** Retained revisions in order. */
    revisions: LoonFS.FileRevision[];
}
