// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Change-feed response after a cursor.
 */
export interface ListChangesResponse {
    /** Exclusive cursor supplied by the caller, or the endpoint's initial position. */
    after_seq: LoonFS.ChangeSeq;
    /** Logical commits after `after_seq`, ordered by ascending namespace sequence. */
    changes: LoonFS.CommittedChange[];
    /** Namespace whose ordered commit stream was read. */
    namespace_id: LoonFS.NamespaceId;
    /** Cursor to request when another page remains, or `None` at `through_seq`. */
    next_after_seq?: LoonFS.ChangeSeq | undefined;
    /** Snapshot head through which this page was evaluated. */
    through_seq: LoonFS.ChangeSeq;
}
