// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * One page of live read snapshots.
 */
export interface ListSnapshotsResponse {
    /** Namespace the snapshots belong to. */
    namespace_id: LoonFS.NamespaceId;
    /** Opaque cursor for the next page. */
    next_cursor?: string | undefined;
    /** Live snapshot records in ascending snapshot-id order. */
    snapshots: LoonFS.Snapshot[];
}
