// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Client-facing direct transfer capability.
 */
export type ObjectTransferAccess = LoonFS.ObjectTransferAccess.PresignedUrl;

export namespace ObjectTransferAccess {
    export interface PresignedUrl extends LoonFS.ObjectTransferAccessPresignedUrl {
        kind: "presigned_url";
    }
}
