// This file was auto-generated by Fern from our API Definition.

/**
 * Short-lived URL plus required headers for one object-store write.
 */
export interface ObjectTransferAccessPresignedUrl {
    /** Expiration timestamp in Unix milliseconds. */
    expires_at_ms: number;
    /** Headers that are covered by the signature and must be sent. */
    headers?: Record<string, string> | undefined;
    /** HTTP method the client must use. */
    method: string;
    /** Full presigned URL. */
    url: string;
}
