// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * A directory without a revision payload.
 */
export interface PathEntryDirectory {
    /**
     * The complete attribute map at `attributes_revision_no`, including an empty map
     * for the initial state.
     */
    attributes?: LoonFS.Attributes | undefined;
    /** The attribute revision this projection represents. */
    attributes_revision_no?: LoonFS.AttributeRevisionNo | undefined;
    /**
     * The latest attribute update time in Unix milliseconds, or `None` for the
     * initial empty state.
     */
    attributes_updated_at_ms?: number | undefined;
    /**
     * The actor responsible for the latest attribute update, or `None` for the
     * initial empty state.
     */
    attributes_updated_by?: LoonFS.ActorId | undefined;
    /** The opaque ID for the current parent and name binding, or `None` for the namespace root. */
    binding_generation?: LoonFS.BindingGeneration | undefined;
    /** The inode creation time in Unix milliseconds. */
    created_at_ms: number;
    /** Actor that created this inode, as supplied by the application. */
    created_by: LoonFS.ActorId;
    /** Stored display name for this path component, absent for the nameless root. */
    display_name?: LoonFS.DisplayName | undefined;
    /** Namespace head sequence this answer was read from. */
    head_seq: LoonFS.ChangeSeq;
    /** Stable inode identity for this item. */
    inode_id: LoonFS.InodeId;
    /** Namespace that was read. */
    namespace_id: LoonFS.NamespaceId;
    /** Parent directory inode, or `None` for the root. */
    parent_inode_id?: LoonFS.InodeId | undefined;
    /** Absolute path as rendered from stored display names. */
    path: LoonFS.AbsolutePath;
}
