// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Result of releasing a read snapshot.
 */
export interface ReleaseSnapshotResponse {
    /** Namespace the snapshot belonged to. */
    namespace_id: LoonFS.NamespaceId;
    /** Released snapshot id. */
    snapshot_id: LoonFS.CheckpointId;
}
