// This file was auto-generated by Fern from our API Definition.

/**
 * Revision number for a file's content. It increases whenever the content is replaced or restored.
 */
export type RevisionNo = number;
