// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * HTTP error body used by LoonFS APIs.
 */
export interface ServiceUnavailableErrorBody {
    /**
     * Stable machine-readable reason from the [`ErrorCode`](crate::ErrorCode)
     * registry.
     *
     * Carried as a string so clients keep working when a newer server
     * introduces a code they do not know; use
     * [`ErrorCode::parse`](crate::ErrorCode::parse) for typed access.
     */
    code: string;
    /**
     * Structured context for the code, present when the failure carries
     * machine-usable identity (API spec, "Standard error contract"). Boxed
     * so the rare detailed error does not widen every error-carrying result.
     */
    details?: LoonFS.ErrorDetails | undefined;
    /**
     * For `not_supported` errors, the capability-document feature key the
     * client should reconcile against.
     */
    feature?: string | undefined;
    /** Human-readable error message. */
    message: string;
    /**
     * Identifies the invalid input. Body fields use JSON Pointer paths;
     * query and path parameters use their names; CLI errors use the flag or
     * argument as written.
     */
    param?: string | undefined;
    /**
     * Correlation id the server assigned to the failed request; the same
     * value is sent as the `x-request-id` response header.
     */
    request_id?: string | undefined;
}
