// This file was auto-generated by Fern from our API Definition.

/**
 * Id of a snapshot.
 *
 * A snapshot is backed by a checkpoint record and uses that record's
 * id, `pin_{manifest_no:020}-{16 lowercase hex}`.
 */
export type SnapshotId = string;
