// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Response after uploading bytes into a session.
 */
export interface UploadContentResponse {
    /** Digest and byte length computed from the accepted body. */
    content_ref: LoonFS.ContentRef;
    /** Namespace that owns the upload session. */
    namespace_id: LoonFS.NamespaceId;
    /** Session into which the service staged these bytes. */
    upload_id: LoonFS.UploadId;
}
