// This file was auto-generated by Fern from our API Definition.

/**
 * Accepting content until its lease passes.
 */
export interface UploadSessionStatusOpen {
    /**
     * Unix-millisecond instant after which the session is abandoned and
     * may be aborted by server-side cleanup.
     */
    expires_at_ms: number;
}
