// This file was auto-generated by Fern from our API Definition.

import type * as LoonFS from "../index.js";

/**
 * Final: the content is durable and verified.
 */
export interface UploadSessionStatusCompleted {
    /** Unix-millisecond stamp of the completion. */
    completed_at_ms: number;
    /** Verified content selected by this session. */
    content_ref: LoonFS.ContentRef;
    /**
     * Fresh proof for a later commit. This is absent after the token
     * minting window closes, while `content_ref` remains available.
     */
    content_token?: LoonFS.ContentToken | undefined;
    /** Transport selected when the session began. */
    mode: LoonFS.UploadMode;
    /** Namespace that owns the session. */
    namespace_id: LoonFS.NamespaceId;
    /** Session represented by this view. */
    upload_id: LoonFS.UploadId;
}
